// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: egoMapData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_egoMapData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_egoMapData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_egoMapData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_egoMapData_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_egoMapData_2eproto;
namespace sim_msg {
class EgoMapData;
class EgoMapDataDefaultTypeInternal;
extern EgoMapDataDefaultTypeInternal _EgoMapData_default_instance_;
class EgoMapData_Lane;
class EgoMapData_LaneDefaultTypeInternal;
extern EgoMapData_LaneDefaultTypeInternal _EgoMapData_Lane_default_instance_;
class EgoMapData_Link;
class EgoMapData_LinkDefaultTypeInternal;
extern EgoMapData_LinkDefaultTypeInternal _EgoMapData_Link_default_instance_;
class EgoMapData_RouteNode;
class EgoMapData_RouteNodeDefaultTypeInternal;
extern EgoMapData_RouteNodeDefaultTypeInternal _EgoMapData_RouteNode_default_instance_;
class EgoMapData_WayPoint;
class EgoMapData_WayPointDefaultTypeInternal;
extern EgoMapData_WayPointDefaultTypeInternal _EgoMapData_WayPoint_default_instance_;
}  // namespace sim_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::sim_msg::EgoMapData* Arena::CreateMaybeMessage<::sim_msg::EgoMapData>(Arena*);
template<> ::sim_msg::EgoMapData_Lane* Arena::CreateMaybeMessage<::sim_msg::EgoMapData_Lane>(Arena*);
template<> ::sim_msg::EgoMapData_Link* Arena::CreateMaybeMessage<::sim_msg::EgoMapData_Link>(Arena*);
template<> ::sim_msg::EgoMapData_RouteNode* Arena::CreateMaybeMessage<::sim_msg::EgoMapData_RouteNode>(Arena*);
template<> ::sim_msg::EgoMapData_WayPoint* Arena::CreateMaybeMessage<::sim_msg::EgoMapData_WayPoint>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sim_msg {

enum EgoMapData_RouteNode_Type : int {
  EgoMapData_RouteNode_Type_TYPE_UNKNOWN = 0,
  EgoMapData_RouteNode_Type_TYPE_LANE = 1,
  EgoMapData_RouteNode_Type_TYPE_LINK = 2,
  EgoMapData_RouteNode_Type_EgoMapData_RouteNode_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  EgoMapData_RouteNode_Type_EgoMapData_RouteNode_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool EgoMapData_RouteNode_Type_IsValid(int value);
constexpr EgoMapData_RouteNode_Type EgoMapData_RouteNode_Type_Type_MIN = EgoMapData_RouteNode_Type_TYPE_UNKNOWN;
constexpr EgoMapData_RouteNode_Type EgoMapData_RouteNode_Type_Type_MAX = EgoMapData_RouteNode_Type_TYPE_LINK;
constexpr int EgoMapData_RouteNode_Type_Type_ARRAYSIZE = EgoMapData_RouteNode_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EgoMapData_RouteNode_Type_descriptor();
template<typename T>
inline const std::string& EgoMapData_RouteNode_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EgoMapData_RouteNode_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EgoMapData_RouteNode_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EgoMapData_RouteNode_Type_descriptor(), enum_t_value);
}
inline bool EgoMapData_RouteNode_Type_Parse(
    const std::string& name, EgoMapData_RouteNode_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EgoMapData_RouteNode_Type>(
    EgoMapData_RouteNode_Type_descriptor(), name, value);
}
enum EgoMapData_LANE_ARROW : int {
  EgoMapData_LANE_ARROW_LANE_ARROW_None = 0,
  EgoMapData_LANE_ARROW_LANE_ARROW_Straight = 1,
  EgoMapData_LANE_ARROW_LANE_ARROW_Left = 2,
  EgoMapData_LANE_ARROW_LANE_ARROW_Right = 3,
  EgoMapData_LANE_ARROW_LANE_ARROW_Uturn = 4,
  EgoMapData_LANE_ARROW_LANE_ARROW_SkewLeft = 5,
  EgoMapData_LANE_ARROW_LANE_ARROW_SkewRight = 6,
  EgoMapData_LANE_ARROW_LANE_ARROW_StraightLeft = 7,
  EgoMapData_LANE_ARROW_LANE_ARROW_StraightRight = 8,
  EgoMapData_LANE_ARROW_LANE_ARROW_LeftRight = 9,
  EgoMapData_LANE_ARROW_LANE_ARROW_LeftUturn = 10,
  EgoMapData_LANE_ARROW_LANE_ARROW_StraightUturn = 11,
  EgoMapData_LANE_ARROW_EgoMapData_LANE_ARROW_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  EgoMapData_LANE_ARROW_EgoMapData_LANE_ARROW_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool EgoMapData_LANE_ARROW_IsValid(int value);
constexpr EgoMapData_LANE_ARROW EgoMapData_LANE_ARROW_LANE_ARROW_MIN = EgoMapData_LANE_ARROW_LANE_ARROW_None;
constexpr EgoMapData_LANE_ARROW EgoMapData_LANE_ARROW_LANE_ARROW_MAX = EgoMapData_LANE_ARROW_LANE_ARROW_StraightUturn;
constexpr int EgoMapData_LANE_ARROW_LANE_ARROW_ARRAYSIZE = EgoMapData_LANE_ARROW_LANE_ARROW_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EgoMapData_LANE_ARROW_descriptor();
template<typename T>
inline const std::string& EgoMapData_LANE_ARROW_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EgoMapData_LANE_ARROW>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EgoMapData_LANE_ARROW_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EgoMapData_LANE_ARROW_descriptor(), enum_t_value);
}
inline bool EgoMapData_LANE_ARROW_Parse(
    const std::string& name, EgoMapData_LANE_ARROW* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EgoMapData_LANE_ARROW>(
    EgoMapData_LANE_ARROW_descriptor(), name, value);
}
// ===================================================================

class EgoMapData_WayPoint :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sim_msg.EgoMapData.WayPoint) */ {
 public:
  EgoMapData_WayPoint();
  virtual ~EgoMapData_WayPoint();

  EgoMapData_WayPoint(const EgoMapData_WayPoint& from);
  EgoMapData_WayPoint(EgoMapData_WayPoint&& from) noexcept
    : EgoMapData_WayPoint() {
    *this = ::std::move(from);
  }

  inline EgoMapData_WayPoint& operator=(const EgoMapData_WayPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline EgoMapData_WayPoint& operator=(EgoMapData_WayPoint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EgoMapData_WayPoint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EgoMapData_WayPoint* internal_default_instance() {
    return reinterpret_cast<const EgoMapData_WayPoint*>(
               &_EgoMapData_WayPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EgoMapData_WayPoint& a, EgoMapData_WayPoint& b) {
    a.Swap(&b);
  }
  inline void Swap(EgoMapData_WayPoint* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EgoMapData_WayPoint* New() const final {
    return CreateMaybeMessage<EgoMapData_WayPoint>(nullptr);
  }

  EgoMapData_WayPoint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EgoMapData_WayPoint>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EgoMapData_WayPoint& from);
  void MergeFrom(const EgoMapData_WayPoint& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EgoMapData_WayPoint* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sim_msg.EgoMapData.WayPoint";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_egoMapData_2eproto);
    return ::descriptor_table_egoMapData_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLonFieldNumber = 1,
    kLatFieldNumber = 2,
  };
  // double lon = 1;
  void clear_lon();
  double lon() const;
  void set_lon(double value);

  // double lat = 2;
  void clear_lat();
  double lat() const;
  void set_lat(double value);

  // @@protoc_insertion_point(class_scope:sim_msg.EgoMapData.WayPoint)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  double lon_;
  double lat_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_egoMapData_2eproto;
};
// -------------------------------------------------------------------

class EgoMapData_Lane :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sim_msg.EgoMapData.Lane) */ {
 public:
  EgoMapData_Lane();
  virtual ~EgoMapData_Lane();

  EgoMapData_Lane(const EgoMapData_Lane& from);
  EgoMapData_Lane(EgoMapData_Lane&& from) noexcept
    : EgoMapData_Lane() {
    *this = ::std::move(from);
  }

  inline EgoMapData_Lane& operator=(const EgoMapData_Lane& from) {
    CopyFrom(from);
    return *this;
  }
  inline EgoMapData_Lane& operator=(EgoMapData_Lane&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EgoMapData_Lane& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EgoMapData_Lane* internal_default_instance() {
    return reinterpret_cast<const EgoMapData_Lane*>(
               &_EgoMapData_Lane_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EgoMapData_Lane& a, EgoMapData_Lane& b) {
    a.Swap(&b);
  }
  inline void Swap(EgoMapData_Lane* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EgoMapData_Lane* New() const final {
    return CreateMaybeMessage<EgoMapData_Lane>(nullptr);
  }

  EgoMapData_Lane* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EgoMapData_Lane>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EgoMapData_Lane& from);
  void MergeFrom(const EgoMapData_Lane& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EgoMapData_Lane* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sim_msg.EgoMapData.Lane";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_egoMapData_2eproto);
    return ::descriptor_table_egoMapData_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWaypointsFieldNumber = 5,
    kRoadIdFieldNumber = 1,
    kLaneIdFieldNumber = 2,
    kLengthFieldNumber = 4,
    kArrowFieldNumber = 3,
  };
  // repeated .sim_msg.EgoMapData.WayPoint waypoints = 5;
  int waypoints_size() const;
  void clear_waypoints();
  ::sim_msg::EgoMapData_WayPoint* mutable_waypoints(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_WayPoint >*
      mutable_waypoints();
  const ::sim_msg::EgoMapData_WayPoint& waypoints(int index) const;
  ::sim_msg::EgoMapData_WayPoint* add_waypoints();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_WayPoint >&
      waypoints() const;

  // uint64 road_id = 1;
  void clear_road_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 road_id() const;
  void set_road_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // int64 lane_id = 2;
  void clear_lane_id();
  ::PROTOBUF_NAMESPACE_ID::int64 lane_id() const;
  void set_lane_id(::PROTOBUF_NAMESPACE_ID::int64 value);

  // double length = 4;
  void clear_length();
  double length() const;
  void set_length(double value);

  // .sim_msg.EgoMapData.LANE_ARROW arrow = 3;
  void clear_arrow();
  ::sim_msg::EgoMapData_LANE_ARROW arrow() const;
  void set_arrow(::sim_msg::EgoMapData_LANE_ARROW value);

  // @@protoc_insertion_point(class_scope:sim_msg.EgoMapData.Lane)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_WayPoint > waypoints_;
  ::PROTOBUF_NAMESPACE_ID::uint64 road_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 lane_id_;
  double length_;
  int arrow_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_egoMapData_2eproto;
};
// -------------------------------------------------------------------

class EgoMapData_Link :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sim_msg.EgoMapData.Link) */ {
 public:
  EgoMapData_Link();
  virtual ~EgoMapData_Link();

  EgoMapData_Link(const EgoMapData_Link& from);
  EgoMapData_Link(EgoMapData_Link&& from) noexcept
    : EgoMapData_Link() {
    *this = ::std::move(from);
  }

  inline EgoMapData_Link& operator=(const EgoMapData_Link& from) {
    CopyFrom(from);
    return *this;
  }
  inline EgoMapData_Link& operator=(EgoMapData_Link&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EgoMapData_Link& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EgoMapData_Link* internal_default_instance() {
    return reinterpret_cast<const EgoMapData_Link*>(
               &_EgoMapData_Link_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(EgoMapData_Link& a, EgoMapData_Link& b) {
    a.Swap(&b);
  }
  inline void Swap(EgoMapData_Link* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EgoMapData_Link* New() const final {
    return CreateMaybeMessage<EgoMapData_Link>(nullptr);
  }

  EgoMapData_Link* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EgoMapData_Link>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EgoMapData_Link& from);
  void MergeFrom(const EgoMapData_Link& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EgoMapData_Link* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sim_msg.EgoMapData.Link";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_egoMapData_2eproto);
    return ::descriptor_table_egoMapData_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWaypointsFieldNumber = 10,
    kLinkIdFieldNumber = 1,
    kFromRoadIdFieldNumber = 2,
    kFromSectionIdFieldNumber = 3,
    kFromLaneIdFieldNumber = 4,
    kToRoadIdFieldNumber = 5,
    kToSectionIdFieldNumber = 6,
    kToLaneIdFieldNumber = 7,
    kJunctionIdFieldNumber = 8,
    kLengthFieldNumber = 9,
  };
  // repeated .sim_msg.EgoMapData.WayPoint waypoints = 10;
  int waypoints_size() const;
  void clear_waypoints();
  ::sim_msg::EgoMapData_WayPoint* mutable_waypoints(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_WayPoint >*
      mutable_waypoints();
  const ::sim_msg::EgoMapData_WayPoint& waypoints(int index) const;
  ::sim_msg::EgoMapData_WayPoint* add_waypoints();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_WayPoint >&
      waypoints() const;

  // uint64 link_id = 1;
  void clear_link_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 link_id() const;
  void set_link_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // uint64 from_road_id = 2;
  void clear_from_road_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 from_road_id() const;
  void set_from_road_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // uint64 from_section_id = 3;
  void clear_from_section_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 from_section_id() const;
  void set_from_section_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // int64 from_lane_id = 4;
  void clear_from_lane_id();
  ::PROTOBUF_NAMESPACE_ID::int64 from_lane_id() const;
  void set_from_lane_id(::PROTOBUF_NAMESPACE_ID::int64 value);

  // uint64 to_road_id = 5;
  void clear_to_road_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 to_road_id() const;
  void set_to_road_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // uint64 to_section_id = 6;
  void clear_to_section_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 to_section_id() const;
  void set_to_section_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // int64 to_lane_id = 7;
  void clear_to_lane_id();
  ::PROTOBUF_NAMESPACE_ID::int64 to_lane_id() const;
  void set_to_lane_id(::PROTOBUF_NAMESPACE_ID::int64 value);

  // uint64 junction_id = 8;
  void clear_junction_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 junction_id() const;
  void set_junction_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // double length = 9;
  void clear_length();
  double length() const;
  void set_length(double value);

  // @@protoc_insertion_point(class_scope:sim_msg.EgoMapData.Link)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_WayPoint > waypoints_;
  ::PROTOBUF_NAMESPACE_ID::uint64 link_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 from_road_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 from_section_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 from_lane_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 to_road_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 to_section_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 to_lane_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 junction_id_;
  double length_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_egoMapData_2eproto;
};
// -------------------------------------------------------------------

class EgoMapData_RouteNode :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sim_msg.EgoMapData.RouteNode) */ {
 public:
  EgoMapData_RouteNode();
  virtual ~EgoMapData_RouteNode();

  EgoMapData_RouteNode(const EgoMapData_RouteNode& from);
  EgoMapData_RouteNode(EgoMapData_RouteNode&& from) noexcept
    : EgoMapData_RouteNode() {
    *this = ::std::move(from);
  }

  inline EgoMapData_RouteNode& operator=(const EgoMapData_RouteNode& from) {
    CopyFrom(from);
    return *this;
  }
  inline EgoMapData_RouteNode& operator=(EgoMapData_RouteNode&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EgoMapData_RouteNode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EgoMapData_RouteNode* internal_default_instance() {
    return reinterpret_cast<const EgoMapData_RouteNode*>(
               &_EgoMapData_RouteNode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(EgoMapData_RouteNode& a, EgoMapData_RouteNode& b) {
    a.Swap(&b);
  }
  inline void Swap(EgoMapData_RouteNode* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EgoMapData_RouteNode* New() const final {
    return CreateMaybeMessage<EgoMapData_RouteNode>(nullptr);
  }

  EgoMapData_RouteNode* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EgoMapData_RouteNode>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EgoMapData_RouteNode& from);
  void MergeFrom(const EgoMapData_RouteNode& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EgoMapData_RouteNode* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sim_msg.EgoMapData.RouteNode";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_egoMapData_2eproto);
    return ::descriptor_table_egoMapData_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef EgoMapData_RouteNode_Type Type;
  static constexpr Type TYPE_UNKNOWN =
    EgoMapData_RouteNode_Type_TYPE_UNKNOWN;
  static constexpr Type TYPE_LANE =
    EgoMapData_RouteNode_Type_TYPE_LANE;
  static constexpr Type TYPE_LINK =
    EgoMapData_RouteNode_Type_TYPE_LINK;
  static inline bool Type_IsValid(int value) {
    return EgoMapData_RouteNode_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    EgoMapData_RouteNode_Type_Type_MIN;
  static constexpr Type Type_MAX =
    EgoMapData_RouteNode_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    EgoMapData_RouteNode_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return EgoMapData_RouteNode_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return EgoMapData_RouteNode_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(const std::string& name,
      Type* value) {
    return EgoMapData_RouteNode_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kLaneFieldNumber = 2,
    kLinkFieldNumber = 3,
    kTypeFieldNumber = 1,
  };
  // .sim_msg.EgoMapData.Lane lane = 2;
  bool has_lane() const;
  void clear_lane();
  const ::sim_msg::EgoMapData_Lane& lane() const;
  ::sim_msg::EgoMapData_Lane* release_lane();
  ::sim_msg::EgoMapData_Lane* mutable_lane();
  void set_allocated_lane(::sim_msg::EgoMapData_Lane* lane);

  // .sim_msg.EgoMapData.Link link = 3;
  bool has_link() const;
  void clear_link();
  const ::sim_msg::EgoMapData_Link& link() const;
  ::sim_msg::EgoMapData_Link* release_link();
  ::sim_msg::EgoMapData_Link* mutable_link();
  void set_allocated_link(::sim_msg::EgoMapData_Link* link);

  // .sim_msg.EgoMapData.RouteNode.Type type = 1;
  void clear_type();
  ::sim_msg::EgoMapData_RouteNode_Type type() const;
  void set_type(::sim_msg::EgoMapData_RouteNode_Type value);

  // @@protoc_insertion_point(class_scope:sim_msg.EgoMapData.RouteNode)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::sim_msg::EgoMapData_Lane* lane_;
  ::sim_msg::EgoMapData_Link* link_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_egoMapData_2eproto;
};
// -------------------------------------------------------------------

class EgoMapData :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sim_msg.EgoMapData) */ {
 public:
  EgoMapData();
  virtual ~EgoMapData();

  EgoMapData(const EgoMapData& from);
  EgoMapData(EgoMapData&& from) noexcept
    : EgoMapData() {
    *this = ::std::move(from);
  }

  inline EgoMapData& operator=(const EgoMapData& from) {
    CopyFrom(from);
    return *this;
  }
  inline EgoMapData& operator=(EgoMapData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EgoMapData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EgoMapData* internal_default_instance() {
    return reinterpret_cast<const EgoMapData*>(
               &_EgoMapData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(EgoMapData& a, EgoMapData& b) {
    a.Swap(&b);
  }
  inline void Swap(EgoMapData* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EgoMapData* New() const final {
    return CreateMaybeMessage<EgoMapData>(nullptr);
  }

  EgoMapData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EgoMapData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EgoMapData& from);
  void MergeFrom(const EgoMapData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EgoMapData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sim_msg.EgoMapData";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_egoMapData_2eproto);
    return ::descriptor_table_egoMapData_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef EgoMapData_WayPoint WayPoint;
  typedef EgoMapData_Lane Lane;
  typedef EgoMapData_Link Link;
  typedef EgoMapData_RouteNode RouteNode;

  typedef EgoMapData_LANE_ARROW LANE_ARROW;
  static constexpr LANE_ARROW LANE_ARROW_None =
    EgoMapData_LANE_ARROW_LANE_ARROW_None;
  static constexpr LANE_ARROW LANE_ARROW_Straight =
    EgoMapData_LANE_ARROW_LANE_ARROW_Straight;
  static constexpr LANE_ARROW LANE_ARROW_Left =
    EgoMapData_LANE_ARROW_LANE_ARROW_Left;
  static constexpr LANE_ARROW LANE_ARROW_Right =
    EgoMapData_LANE_ARROW_LANE_ARROW_Right;
  static constexpr LANE_ARROW LANE_ARROW_Uturn =
    EgoMapData_LANE_ARROW_LANE_ARROW_Uturn;
  static constexpr LANE_ARROW LANE_ARROW_SkewLeft =
    EgoMapData_LANE_ARROW_LANE_ARROW_SkewLeft;
  static constexpr LANE_ARROW LANE_ARROW_SkewRight =
    EgoMapData_LANE_ARROW_LANE_ARROW_SkewRight;
  static constexpr LANE_ARROW LANE_ARROW_StraightLeft =
    EgoMapData_LANE_ARROW_LANE_ARROW_StraightLeft;
  static constexpr LANE_ARROW LANE_ARROW_StraightRight =
    EgoMapData_LANE_ARROW_LANE_ARROW_StraightRight;
  static constexpr LANE_ARROW LANE_ARROW_LeftRight =
    EgoMapData_LANE_ARROW_LANE_ARROW_LeftRight;
  static constexpr LANE_ARROW LANE_ARROW_LeftUturn =
    EgoMapData_LANE_ARROW_LANE_ARROW_LeftUturn;
  static constexpr LANE_ARROW LANE_ARROW_StraightUturn =
    EgoMapData_LANE_ARROW_LANE_ARROW_StraightUturn;
  static inline bool LANE_ARROW_IsValid(int value) {
    return EgoMapData_LANE_ARROW_IsValid(value);
  }
  static constexpr LANE_ARROW LANE_ARROW_MIN =
    EgoMapData_LANE_ARROW_LANE_ARROW_MIN;
  static constexpr LANE_ARROW LANE_ARROW_MAX =
    EgoMapData_LANE_ARROW_LANE_ARROW_MAX;
  static constexpr int LANE_ARROW_ARRAYSIZE =
    EgoMapData_LANE_ARROW_LANE_ARROW_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  LANE_ARROW_descriptor() {
    return EgoMapData_LANE_ARROW_descriptor();
  }
  template<typename T>
  static inline const std::string& LANE_ARROW_Name(T enum_t_value) {
    static_assert(::std::is_same<T, LANE_ARROW>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function LANE_ARROW_Name.");
    return EgoMapData_LANE_ARROW_Name(enum_t_value);
  }
  static inline bool LANE_ARROW_Parse(const std::string& name,
      LANE_ARROW* value) {
    return EgoMapData_LANE_ARROW_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kRouteNodesFieldNumber = 2,
    kHeaderFieldNumber = 1,
    kSFieldNumber = 5,
    kLFieldNumber = 6,
    kYawFieldNumber = 7,
    kDisToEndFieldNumber = 8,
    kOnLaneFieldNumber = 3,
    kOnLinkFieldNumber = 4,
  };
  // repeated .sim_msg.EgoMapData.RouteNode route_nodes = 2;
  int route_nodes_size() const;
  void clear_route_nodes();
  ::sim_msg::EgoMapData_RouteNode* mutable_route_nodes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_RouteNode >*
      mutable_route_nodes();
  const ::sim_msg::EgoMapData_RouteNode& route_nodes(int index) const;
  ::sim_msg::EgoMapData_RouteNode* add_route_nodes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_RouteNode >&
      route_nodes() const;

  // .sim_msg.Header header = 1;
  bool has_header() const;
  void clear_header();
  const ::sim_msg::Header& header() const;
  ::sim_msg::Header* release_header();
  ::sim_msg::Header* mutable_header();
  void set_allocated_header(::sim_msg::Header* header);

  // double s = 5;
  void clear_s();
  double s() const;
  void set_s(double value);

  // double l = 6;
  void clear_l();
  double l() const;
  void set_l(double value);

  // double yaw = 7;
  void clear_yaw();
  double yaw() const;
  void set_yaw(double value);

  // double dis_to_end = 8;
  void clear_dis_to_end();
  double dis_to_end() const;
  void set_dis_to_end(double value);

  // bool on_lane = 3;
  void clear_on_lane();
  bool on_lane() const;
  void set_on_lane(bool value);

  // bool on_link = 4;
  void clear_on_link();
  bool on_link() const;
  void set_on_link(bool value);

  // @@protoc_insertion_point(class_scope:sim_msg.EgoMapData)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_RouteNode > route_nodes_;
  ::sim_msg::Header* header_;
  double s_;
  double l_;
  double yaw_;
  double dis_to_end_;
  bool on_lane_;
  bool on_link_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_egoMapData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EgoMapData_WayPoint

// double lon = 1;
inline void EgoMapData_WayPoint::clear_lon() {
  lon_ = 0;
}
inline double EgoMapData_WayPoint::lon() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.WayPoint.lon)
  return lon_;
}
inline void EgoMapData_WayPoint::set_lon(double value) {
  
  lon_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.WayPoint.lon)
}

// double lat = 2;
inline void EgoMapData_WayPoint::clear_lat() {
  lat_ = 0;
}
inline double EgoMapData_WayPoint::lat() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.WayPoint.lat)
  return lat_;
}
inline void EgoMapData_WayPoint::set_lat(double value) {
  
  lat_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.WayPoint.lat)
}

// -------------------------------------------------------------------

// EgoMapData_Lane

// uint64 road_id = 1;
inline void EgoMapData_Lane::clear_road_id() {
  road_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EgoMapData_Lane::road_id() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Lane.road_id)
  return road_id_;
}
inline void EgoMapData_Lane::set_road_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  road_id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Lane.road_id)
}

// int64 lane_id = 2;
inline void EgoMapData_Lane::clear_lane_id() {
  lane_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EgoMapData_Lane::lane_id() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Lane.lane_id)
  return lane_id_;
}
inline void EgoMapData_Lane::set_lane_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  lane_id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Lane.lane_id)
}

// .sim_msg.EgoMapData.LANE_ARROW arrow = 3;
inline void EgoMapData_Lane::clear_arrow() {
  arrow_ = 0;
}
inline ::sim_msg::EgoMapData_LANE_ARROW EgoMapData_Lane::arrow() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Lane.arrow)
  return static_cast< ::sim_msg::EgoMapData_LANE_ARROW >(arrow_);
}
inline void EgoMapData_Lane::set_arrow(::sim_msg::EgoMapData_LANE_ARROW value) {
  
  arrow_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Lane.arrow)
}

// double length = 4;
inline void EgoMapData_Lane::clear_length() {
  length_ = 0;
}
inline double EgoMapData_Lane::length() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Lane.length)
  return length_;
}
inline void EgoMapData_Lane::set_length(double value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Lane.length)
}

// repeated .sim_msg.EgoMapData.WayPoint waypoints = 5;
inline int EgoMapData_Lane::waypoints_size() const {
  return waypoints_.size();
}
inline void EgoMapData_Lane::clear_waypoints() {
  waypoints_.Clear();
}
inline ::sim_msg::EgoMapData_WayPoint* EgoMapData_Lane::mutable_waypoints(int index) {
  // @@protoc_insertion_point(field_mutable:sim_msg.EgoMapData.Lane.waypoints)
  return waypoints_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_WayPoint >*
EgoMapData_Lane::mutable_waypoints() {
  // @@protoc_insertion_point(field_mutable_list:sim_msg.EgoMapData.Lane.waypoints)
  return &waypoints_;
}
inline const ::sim_msg::EgoMapData_WayPoint& EgoMapData_Lane::waypoints(int index) const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Lane.waypoints)
  return waypoints_.Get(index);
}
inline ::sim_msg::EgoMapData_WayPoint* EgoMapData_Lane::add_waypoints() {
  // @@protoc_insertion_point(field_add:sim_msg.EgoMapData.Lane.waypoints)
  return waypoints_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_WayPoint >&
EgoMapData_Lane::waypoints() const {
  // @@protoc_insertion_point(field_list:sim_msg.EgoMapData.Lane.waypoints)
  return waypoints_;
}

// -------------------------------------------------------------------

// EgoMapData_Link

// uint64 link_id = 1;
inline void EgoMapData_Link::clear_link_id() {
  link_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EgoMapData_Link::link_id() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Link.link_id)
  return link_id_;
}
inline void EgoMapData_Link::set_link_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  link_id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Link.link_id)
}

// uint64 from_road_id = 2;
inline void EgoMapData_Link::clear_from_road_id() {
  from_road_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EgoMapData_Link::from_road_id() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Link.from_road_id)
  return from_road_id_;
}
inline void EgoMapData_Link::set_from_road_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  from_road_id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Link.from_road_id)
}

// uint64 from_section_id = 3;
inline void EgoMapData_Link::clear_from_section_id() {
  from_section_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EgoMapData_Link::from_section_id() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Link.from_section_id)
  return from_section_id_;
}
inline void EgoMapData_Link::set_from_section_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  from_section_id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Link.from_section_id)
}

// int64 from_lane_id = 4;
inline void EgoMapData_Link::clear_from_lane_id() {
  from_lane_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EgoMapData_Link::from_lane_id() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Link.from_lane_id)
  return from_lane_id_;
}
inline void EgoMapData_Link::set_from_lane_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  from_lane_id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Link.from_lane_id)
}

// uint64 to_road_id = 5;
inline void EgoMapData_Link::clear_to_road_id() {
  to_road_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EgoMapData_Link::to_road_id() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Link.to_road_id)
  return to_road_id_;
}
inline void EgoMapData_Link::set_to_road_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  to_road_id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Link.to_road_id)
}

// uint64 to_section_id = 6;
inline void EgoMapData_Link::clear_to_section_id() {
  to_section_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EgoMapData_Link::to_section_id() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Link.to_section_id)
  return to_section_id_;
}
inline void EgoMapData_Link::set_to_section_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  to_section_id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Link.to_section_id)
}

// int64 to_lane_id = 7;
inline void EgoMapData_Link::clear_to_lane_id() {
  to_lane_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EgoMapData_Link::to_lane_id() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Link.to_lane_id)
  return to_lane_id_;
}
inline void EgoMapData_Link::set_to_lane_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  to_lane_id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Link.to_lane_id)
}

// uint64 junction_id = 8;
inline void EgoMapData_Link::clear_junction_id() {
  junction_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EgoMapData_Link::junction_id() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Link.junction_id)
  return junction_id_;
}
inline void EgoMapData_Link::set_junction_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  junction_id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Link.junction_id)
}

// double length = 9;
inline void EgoMapData_Link::clear_length() {
  length_ = 0;
}
inline double EgoMapData_Link::length() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Link.length)
  return length_;
}
inline void EgoMapData_Link::set_length(double value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.Link.length)
}

// repeated .sim_msg.EgoMapData.WayPoint waypoints = 10;
inline int EgoMapData_Link::waypoints_size() const {
  return waypoints_.size();
}
inline void EgoMapData_Link::clear_waypoints() {
  waypoints_.Clear();
}
inline ::sim_msg::EgoMapData_WayPoint* EgoMapData_Link::mutable_waypoints(int index) {
  // @@protoc_insertion_point(field_mutable:sim_msg.EgoMapData.Link.waypoints)
  return waypoints_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_WayPoint >*
EgoMapData_Link::mutable_waypoints() {
  // @@protoc_insertion_point(field_mutable_list:sim_msg.EgoMapData.Link.waypoints)
  return &waypoints_;
}
inline const ::sim_msg::EgoMapData_WayPoint& EgoMapData_Link::waypoints(int index) const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.Link.waypoints)
  return waypoints_.Get(index);
}
inline ::sim_msg::EgoMapData_WayPoint* EgoMapData_Link::add_waypoints() {
  // @@protoc_insertion_point(field_add:sim_msg.EgoMapData.Link.waypoints)
  return waypoints_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_WayPoint >&
EgoMapData_Link::waypoints() const {
  // @@protoc_insertion_point(field_list:sim_msg.EgoMapData.Link.waypoints)
  return waypoints_;
}

// -------------------------------------------------------------------

// EgoMapData_RouteNode

// .sim_msg.EgoMapData.RouteNode.Type type = 1;
inline void EgoMapData_RouteNode::clear_type() {
  type_ = 0;
}
inline ::sim_msg::EgoMapData_RouteNode_Type EgoMapData_RouteNode::type() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.RouteNode.type)
  return static_cast< ::sim_msg::EgoMapData_RouteNode_Type >(type_);
}
inline void EgoMapData_RouteNode::set_type(::sim_msg::EgoMapData_RouteNode_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.RouteNode.type)
}

// .sim_msg.EgoMapData.Lane lane = 2;
inline bool EgoMapData_RouteNode::has_lane() const {
  return this != internal_default_instance() && lane_ != nullptr;
}
inline void EgoMapData_RouteNode::clear_lane() {
  if (GetArenaNoVirtual() == nullptr && lane_ != nullptr) {
    delete lane_;
  }
  lane_ = nullptr;
}
inline const ::sim_msg::EgoMapData_Lane& EgoMapData_RouteNode::lane() const {
  const ::sim_msg::EgoMapData_Lane* p = lane_;
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.RouteNode.lane)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::EgoMapData_Lane*>(
      &::sim_msg::_EgoMapData_Lane_default_instance_);
}
inline ::sim_msg::EgoMapData_Lane* EgoMapData_RouteNode::release_lane() {
  // @@protoc_insertion_point(field_release:sim_msg.EgoMapData.RouteNode.lane)
  
  ::sim_msg::EgoMapData_Lane* temp = lane_;
  lane_ = nullptr;
  return temp;
}
inline ::sim_msg::EgoMapData_Lane* EgoMapData_RouteNode::mutable_lane() {
  
  if (lane_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::EgoMapData_Lane>(GetArenaNoVirtual());
    lane_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.EgoMapData.RouteNode.lane)
  return lane_;
}
inline void EgoMapData_RouteNode::set_allocated_lane(::sim_msg::EgoMapData_Lane* lane) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete lane_;
  }
  if (lane) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      lane = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, lane, submessage_arena);
    }
    
  } else {
    
  }
  lane_ = lane;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.EgoMapData.RouteNode.lane)
}

// .sim_msg.EgoMapData.Link link = 3;
inline bool EgoMapData_RouteNode::has_link() const {
  return this != internal_default_instance() && link_ != nullptr;
}
inline void EgoMapData_RouteNode::clear_link() {
  if (GetArenaNoVirtual() == nullptr && link_ != nullptr) {
    delete link_;
  }
  link_ = nullptr;
}
inline const ::sim_msg::EgoMapData_Link& EgoMapData_RouteNode::link() const {
  const ::sim_msg::EgoMapData_Link* p = link_;
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.RouteNode.link)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::EgoMapData_Link*>(
      &::sim_msg::_EgoMapData_Link_default_instance_);
}
inline ::sim_msg::EgoMapData_Link* EgoMapData_RouteNode::release_link() {
  // @@protoc_insertion_point(field_release:sim_msg.EgoMapData.RouteNode.link)
  
  ::sim_msg::EgoMapData_Link* temp = link_;
  link_ = nullptr;
  return temp;
}
inline ::sim_msg::EgoMapData_Link* EgoMapData_RouteNode::mutable_link() {
  
  if (link_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::EgoMapData_Link>(GetArenaNoVirtual());
    link_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.EgoMapData.RouteNode.link)
  return link_;
}
inline void EgoMapData_RouteNode::set_allocated_link(::sim_msg::EgoMapData_Link* link) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete link_;
  }
  if (link) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      link = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, link, submessage_arena);
    }
    
  } else {
    
  }
  link_ = link;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.EgoMapData.RouteNode.link)
}

// -------------------------------------------------------------------

// EgoMapData

// .sim_msg.Header header = 1;
inline bool EgoMapData::has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline const ::sim_msg::Header& EgoMapData::header() const {
  const ::sim_msg::Header* p = header_;
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Header*>(
      &::sim_msg::_Header_default_instance_);
}
inline ::sim_msg::Header* EgoMapData::release_header() {
  // @@protoc_insertion_point(field_release:sim_msg.EgoMapData.header)
  
  ::sim_msg::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::sim_msg::Header* EgoMapData::mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.EgoMapData.header)
  return header_;
}
inline void EgoMapData::set_allocated_header(::sim_msg::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.EgoMapData.header)
}

// repeated .sim_msg.EgoMapData.RouteNode route_nodes = 2;
inline int EgoMapData::route_nodes_size() const {
  return route_nodes_.size();
}
inline void EgoMapData::clear_route_nodes() {
  route_nodes_.Clear();
}
inline ::sim_msg::EgoMapData_RouteNode* EgoMapData::mutable_route_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:sim_msg.EgoMapData.route_nodes)
  return route_nodes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_RouteNode >*
EgoMapData::mutable_route_nodes() {
  // @@protoc_insertion_point(field_mutable_list:sim_msg.EgoMapData.route_nodes)
  return &route_nodes_;
}
inline const ::sim_msg::EgoMapData_RouteNode& EgoMapData::route_nodes(int index) const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.route_nodes)
  return route_nodes_.Get(index);
}
inline ::sim_msg::EgoMapData_RouteNode* EgoMapData::add_route_nodes() {
  // @@protoc_insertion_point(field_add:sim_msg.EgoMapData.route_nodes)
  return route_nodes_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::EgoMapData_RouteNode >&
EgoMapData::route_nodes() const {
  // @@protoc_insertion_point(field_list:sim_msg.EgoMapData.route_nodes)
  return route_nodes_;
}

// bool on_lane = 3;
inline void EgoMapData::clear_on_lane() {
  on_lane_ = false;
}
inline bool EgoMapData::on_lane() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.on_lane)
  return on_lane_;
}
inline void EgoMapData::set_on_lane(bool value) {
  
  on_lane_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.on_lane)
}

// bool on_link = 4;
inline void EgoMapData::clear_on_link() {
  on_link_ = false;
}
inline bool EgoMapData::on_link() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.on_link)
  return on_link_;
}
inline void EgoMapData::set_on_link(bool value) {
  
  on_link_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.on_link)
}

// double s = 5;
inline void EgoMapData::clear_s() {
  s_ = 0;
}
inline double EgoMapData::s() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.s)
  return s_;
}
inline void EgoMapData::set_s(double value) {
  
  s_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.s)
}

// double l = 6;
inline void EgoMapData::clear_l() {
  l_ = 0;
}
inline double EgoMapData::l() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.l)
  return l_;
}
inline void EgoMapData::set_l(double value) {
  
  l_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.l)
}

// double yaw = 7;
inline void EgoMapData::clear_yaw() {
  yaw_ = 0;
}
inline double EgoMapData::yaw() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.yaw)
  return yaw_;
}
inline void EgoMapData::set_yaw(double value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.yaw)
}

// double dis_to_end = 8;
inline void EgoMapData::clear_dis_to_end() {
  dis_to_end_ = 0;
}
inline double EgoMapData::dis_to_end() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoMapData.dis_to_end)
  return dis_to_end_;
}
inline void EgoMapData::set_dis_to_end(double value) {
  
  dis_to_end_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoMapData.dis_to_end)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sim_msg

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::sim_msg::EgoMapData_RouteNode_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sim_msg::EgoMapData_RouteNode_Type>() {
  return ::sim_msg::EgoMapData_RouteNode_Type_descriptor();
}
template <> struct is_proto_enum< ::sim_msg::EgoMapData_LANE_ARROW> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sim_msg::EgoMapData_LANE_ARROW>() {
  return ::sim_msg::EgoMapData_LANE_ARROW_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_egoMapData_2eproto
