// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: egoMapData.proto

#include "egoMapData.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_egoMapData_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_EgoMapData_Lane_egoMapData_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_egoMapData_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_EgoMapData_Link_egoMapData_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_egoMapData_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_EgoMapData_RouteNode_egoMapData_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_egoMapData_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_EgoMapData_WayPoint_egoMapData_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_header_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Header_header_2eproto;
namespace sim_msg {
class EgoMapData_WayPointDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<EgoMapData_WayPoint> _instance;
} _EgoMapData_WayPoint_default_instance_;
class EgoMapData_LaneDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<EgoMapData_Lane> _instance;
} _EgoMapData_Lane_default_instance_;
class EgoMapData_LinkDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<EgoMapData_Link> _instance;
} _EgoMapData_Link_default_instance_;
class EgoMapData_RouteNodeDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<EgoMapData_RouteNode> _instance;
} _EgoMapData_RouteNode_default_instance_;
class EgoMapDataDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<EgoMapData> _instance;
} _EgoMapData_default_instance_;
}  // namespace sim_msg
static void InitDefaultsscc_info_EgoMapData_egoMapData_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sim_msg::_EgoMapData_default_instance_;
    new (ptr) ::sim_msg::EgoMapData();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sim_msg::EgoMapData::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_EgoMapData_egoMapData_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsscc_info_EgoMapData_egoMapData_2eproto}, {
      &scc_info_Header_header_2eproto.base,
      &scc_info_EgoMapData_RouteNode_egoMapData_2eproto.base,}};

static void InitDefaultsscc_info_EgoMapData_Lane_egoMapData_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sim_msg::_EgoMapData_Lane_default_instance_;
    new (ptr) ::sim_msg::EgoMapData_Lane();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sim_msg::EgoMapData_Lane::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_EgoMapData_Lane_egoMapData_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsscc_info_EgoMapData_Lane_egoMapData_2eproto}, {
      &scc_info_EgoMapData_WayPoint_egoMapData_2eproto.base,}};

static void InitDefaultsscc_info_EgoMapData_Link_egoMapData_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sim_msg::_EgoMapData_Link_default_instance_;
    new (ptr) ::sim_msg::EgoMapData_Link();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sim_msg::EgoMapData_Link::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_EgoMapData_Link_egoMapData_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsscc_info_EgoMapData_Link_egoMapData_2eproto}, {
      &scc_info_EgoMapData_WayPoint_egoMapData_2eproto.base,}};

static void InitDefaultsscc_info_EgoMapData_RouteNode_egoMapData_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sim_msg::_EgoMapData_RouteNode_default_instance_;
    new (ptr) ::sim_msg::EgoMapData_RouteNode();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sim_msg::EgoMapData_RouteNode::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_EgoMapData_RouteNode_egoMapData_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsscc_info_EgoMapData_RouteNode_egoMapData_2eproto}, {
      &scc_info_EgoMapData_Lane_egoMapData_2eproto.base,
      &scc_info_EgoMapData_Link_egoMapData_2eproto.base,}};

static void InitDefaultsscc_info_EgoMapData_WayPoint_egoMapData_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sim_msg::_EgoMapData_WayPoint_default_instance_;
    new (ptr) ::sim_msg::EgoMapData_WayPoint();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sim_msg::EgoMapData_WayPoint::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_EgoMapData_WayPoint_egoMapData_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_EgoMapData_WayPoint_egoMapData_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_egoMapData_2eproto[5];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_egoMapData_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_egoMapData_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_egoMapData_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_WayPoint, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_WayPoint, lon_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_WayPoint, lat_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Lane, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Lane, road_id_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Lane, lane_id_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Lane, arrow_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Lane, length_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Lane, waypoints_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Link, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Link, link_id_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Link, from_road_id_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Link, from_section_id_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Link, from_lane_id_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Link, to_road_id_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Link, to_section_id_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Link, to_lane_id_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Link, junction_id_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Link, length_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_Link, waypoints_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_RouteNode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_RouteNode, type_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_RouteNode, lane_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData_RouteNode, link_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData, header_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData, route_nodes_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData, on_lane_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData, on_link_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData, s_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData, l_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData, yaw_),
  PROTOBUF_FIELD_OFFSET(::sim_msg::EgoMapData, dis_to_end_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::sim_msg::EgoMapData_WayPoint)},
  { 7, -1, sizeof(::sim_msg::EgoMapData_Lane)},
  { 17, -1, sizeof(::sim_msg::EgoMapData_Link)},
  { 32, -1, sizeof(::sim_msg::EgoMapData_RouteNode)},
  { 40, -1, sizeof(::sim_msg::EgoMapData)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::sim_msg::_EgoMapData_WayPoint_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::sim_msg::_EgoMapData_Lane_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::sim_msg::_EgoMapData_Link_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::sim_msg::_EgoMapData_RouteNode_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::sim_msg::_EgoMapData_default_instance_),
};

const char descriptor_table_protodef_egoMapData_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020egoMapData.proto\022\007sim_msg\032\014header.prot"
  "o\"\365\010\n\nEgoMapData\022\037\n\006header\030\001 \001(\0132\017.sim_m"
  "sg.Header\0222\n\013route_nodes\030\002 \003(\0132\035.sim_msg"
  ".EgoMapData.RouteNode\022\017\n\007on_lane\030\003 \001(\010\022\017"
  "\n\007on_link\030\004 \001(\010\022\t\n\001s\030\005 \001(\001\022\t\n\001l\030\006 \001(\001\022\013\n"
  "\003yaw\030\007 \001(\001\022\022\n\ndis_to_end\030\010 \001(\001\032$\n\010WayPoi"
  "nt\022\013\n\003lon\030\001 \001(\001\022\013\n\003lat\030\002 \001(\001\032\230\001\n\004Lane\022\017\n"
  "\007road_id\030\001 \001(\004\022\017\n\007lane_id\030\002 \001(\003\022-\n\005arrow"
  "\030\003 \001(\0162\036.sim_msg.EgoMapData.LANE_ARROW\022\016"
  "\n\006length\030\004 \001(\001\022/\n\twaypoints\030\005 \003(\0132\034.sim_"
  "msg.EgoMapData.WayPoint\032\361\001\n\004Link\022\017\n\007link"
  "_id\030\001 \001(\004\022\024\n\014from_road_id\030\002 \001(\004\022\027\n\017from_"
  "section_id\030\003 \001(\004\022\024\n\014from_lane_id\030\004 \001(\003\022\022"
  "\n\nto_road_id\030\005 \001(\004\022\025\n\rto_section_id\030\006 \001("
  "\004\022\022\n\nto_lane_id\030\007 \001(\003\022\023\n\013junction_id\030\010 \001"
  "(\004\022\016\n\006length\030\t \001(\001\022/\n\twaypoints\030\n \003(\0132\034."
  "sim_msg.EgoMapData.WayPoint\032\305\001\n\tRouteNod"
  "e\0220\n\004type\030\001 \001(\0162\".sim_msg.EgoMapData.Rou"
  "teNode.Type\022&\n\004lane\030\002 \001(\0132\030.sim_msg.EgoM"
  "apData.Lane\022&\n\004link\030\003 \001(\0132\030.sim_msg.EgoM"
  "apData.Link\"6\n\004Type\022\020\n\014TYPE_UNKNOWN\020\000\022\r\n"
  "\tTYPE_LANE\020\001\022\r\n\tTYPE_LINK\020\002\"\273\002\n\nLANE_ARR"
  "OW\022\023\n\017LANE_ARROW_None\020\000\022\027\n\023LANE_ARROW_St"
  "raight\020\001\022\023\n\017LANE_ARROW_Left\020\002\022\024\n\020LANE_AR"
  "ROW_Right\020\003\022\024\n\020LANE_ARROW_Uturn\020\004\022\027\n\023LAN"
  "E_ARROW_SkewLeft\020\005\022\030\n\024LANE_ARROW_SkewRig"
  "ht\020\006\022\033\n\027LANE_ARROW_StraightLeft\020\007\022\034\n\030LAN"
  "E_ARROW_StraightRight\020\010\022\030\n\024LANE_ARROW_Le"
  "ftRight\020\t\022\030\n\024LANE_ARROW_LeftUturn\020\n\022\034\n\030L"
  "ANE_ARROW_StraightUturn\020\013b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_egoMapData_2eproto_deps[1] = {
  &::descriptor_table_header_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_egoMapData_2eproto_sccs[5] = {
  &scc_info_EgoMapData_egoMapData_2eproto.base,
  &scc_info_EgoMapData_Lane_egoMapData_2eproto.base,
  &scc_info_EgoMapData_Link_egoMapData_2eproto.base,
  &scc_info_EgoMapData_RouteNode_egoMapData_2eproto.base,
  &scc_info_EgoMapData_WayPoint_egoMapData_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_egoMapData_2eproto_once;
static bool descriptor_table_egoMapData_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_egoMapData_2eproto = {
  &descriptor_table_egoMapData_2eproto_initialized, descriptor_table_protodef_egoMapData_2eproto, "egoMapData.proto", 1193,
  &descriptor_table_egoMapData_2eproto_once, descriptor_table_egoMapData_2eproto_sccs, descriptor_table_egoMapData_2eproto_deps, 5, 1,
  schemas, file_default_instances, TableStruct_egoMapData_2eproto::offsets,
  file_level_metadata_egoMapData_2eproto, 5, file_level_enum_descriptors_egoMapData_2eproto, file_level_service_descriptors_egoMapData_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_egoMapData_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_egoMapData_2eproto), true);
namespace sim_msg {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EgoMapData_RouteNode_Type_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_egoMapData_2eproto);
  return file_level_enum_descriptors_egoMapData_2eproto[0];
}
bool EgoMapData_RouteNode_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr EgoMapData_RouteNode_Type EgoMapData_RouteNode::TYPE_UNKNOWN;
constexpr EgoMapData_RouteNode_Type EgoMapData_RouteNode::TYPE_LANE;
constexpr EgoMapData_RouteNode_Type EgoMapData_RouteNode::TYPE_LINK;
constexpr EgoMapData_RouteNode_Type EgoMapData_RouteNode::Type_MIN;
constexpr EgoMapData_RouteNode_Type EgoMapData_RouteNode::Type_MAX;
constexpr int EgoMapData_RouteNode::Type_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EgoMapData_LANE_ARROW_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_egoMapData_2eproto);
  return file_level_enum_descriptors_egoMapData_2eproto[1];
}
bool EgoMapData_LANE_ARROW_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_None;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_Straight;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_Left;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_Right;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_Uturn;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_SkewLeft;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_SkewRight;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_StraightLeft;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_StraightRight;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_LeftRight;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_LeftUturn;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_StraightUturn;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_MIN;
constexpr EgoMapData_LANE_ARROW EgoMapData::LANE_ARROW_MAX;
constexpr int EgoMapData::LANE_ARROW_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void EgoMapData_WayPoint::InitAsDefaultInstance() {
}
class EgoMapData_WayPoint::_Internal {
 public:
};

EgoMapData_WayPoint::EgoMapData_WayPoint()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sim_msg.EgoMapData.WayPoint)
}
EgoMapData_WayPoint::EgoMapData_WayPoint(const EgoMapData_WayPoint& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&lon_, &from.lon_,
    static_cast<size_t>(reinterpret_cast<char*>(&lat_) -
    reinterpret_cast<char*>(&lon_)) + sizeof(lat_));
  // @@protoc_insertion_point(copy_constructor:sim_msg.EgoMapData.WayPoint)
}

void EgoMapData_WayPoint::SharedCtor() {
  ::memset(&lon_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&lat_) -
      reinterpret_cast<char*>(&lon_)) + sizeof(lat_));
}

EgoMapData_WayPoint::~EgoMapData_WayPoint() {
  // @@protoc_insertion_point(destructor:sim_msg.EgoMapData.WayPoint)
  SharedDtor();
}

void EgoMapData_WayPoint::SharedDtor() {
}

void EgoMapData_WayPoint::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EgoMapData_WayPoint& EgoMapData_WayPoint::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_EgoMapData_WayPoint_egoMapData_2eproto.base);
  return *internal_default_instance();
}


void EgoMapData_WayPoint::Clear() {
// @@protoc_insertion_point(message_clear_start:sim_msg.EgoMapData.WayPoint)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&lon_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&lat_) -
      reinterpret_cast<char*>(&lon_)) + sizeof(lat_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* EgoMapData_WayPoint::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // double lon = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          lon_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double lat = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          lat_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool EgoMapData_WayPoint::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:sim_msg.EgoMapData.WayPoint)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double lon = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (9 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   double, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &lon_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double lat = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (17 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   double, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &lat_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sim_msg.EgoMapData.WayPoint)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sim_msg.EgoMapData.WayPoint)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void EgoMapData_WayPoint::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sim_msg.EgoMapData.WayPoint)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double lon = 1;
  if (!(this->lon() <= 0 && this->lon() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDouble(1, this->lon(), output);
  }

  // double lat = 2;
  if (!(this->lat() <= 0 && this->lat() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDouble(2, this->lat(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sim_msg.EgoMapData.WayPoint)
}

::PROTOBUF_NAMESPACE_ID::uint8* EgoMapData_WayPoint::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sim_msg.EgoMapData.WayPoint)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double lon = 1;
  if (!(this->lon() <= 0 && this->lon() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->lon(), target);
  }

  // double lat = 2;
  if (!(this->lat() <= 0 && this->lat() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->lat(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sim_msg.EgoMapData.WayPoint)
  return target;
}

size_t EgoMapData_WayPoint::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sim_msg.EgoMapData.WayPoint)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double lon = 1;
  if (!(this->lon() <= 0 && this->lon() >= 0)) {
    total_size += 1 + 8;
  }

  // double lat = 2;
  if (!(this->lat() <= 0 && this->lat() >= 0)) {
    total_size += 1 + 8;
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EgoMapData_WayPoint::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sim_msg.EgoMapData.WayPoint)
  GOOGLE_DCHECK_NE(&from, this);
  const EgoMapData_WayPoint* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EgoMapData_WayPoint>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sim_msg.EgoMapData.WayPoint)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sim_msg.EgoMapData.WayPoint)
    MergeFrom(*source);
  }
}

void EgoMapData_WayPoint::MergeFrom(const EgoMapData_WayPoint& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sim_msg.EgoMapData.WayPoint)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.lon() <= 0 && from.lon() >= 0)) {
    set_lon(from.lon());
  }
  if (!(from.lat() <= 0 && from.lat() >= 0)) {
    set_lat(from.lat());
  }
}

void EgoMapData_WayPoint::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sim_msg.EgoMapData.WayPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EgoMapData_WayPoint::CopyFrom(const EgoMapData_WayPoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sim_msg.EgoMapData.WayPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EgoMapData_WayPoint::IsInitialized() const {
  return true;
}

void EgoMapData_WayPoint::InternalSwap(EgoMapData_WayPoint* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(lon_, other->lon_);
  swap(lat_, other->lat_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EgoMapData_WayPoint::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void EgoMapData_Lane::InitAsDefaultInstance() {
}
class EgoMapData_Lane::_Internal {
 public:
};

EgoMapData_Lane::EgoMapData_Lane()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sim_msg.EgoMapData.Lane)
}
EgoMapData_Lane::EgoMapData_Lane(const EgoMapData_Lane& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      waypoints_(from.waypoints_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&road_id_, &from.road_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&arrow_) -
    reinterpret_cast<char*>(&road_id_)) + sizeof(arrow_));
  // @@protoc_insertion_point(copy_constructor:sim_msg.EgoMapData.Lane)
}

void EgoMapData_Lane::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_EgoMapData_Lane_egoMapData_2eproto.base);
  ::memset(&road_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&arrow_) -
      reinterpret_cast<char*>(&road_id_)) + sizeof(arrow_));
}

EgoMapData_Lane::~EgoMapData_Lane() {
  // @@protoc_insertion_point(destructor:sim_msg.EgoMapData.Lane)
  SharedDtor();
}

void EgoMapData_Lane::SharedDtor() {
}

void EgoMapData_Lane::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EgoMapData_Lane& EgoMapData_Lane::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_EgoMapData_Lane_egoMapData_2eproto.base);
  return *internal_default_instance();
}


void EgoMapData_Lane::Clear() {
// @@protoc_insertion_point(message_clear_start:sim_msg.EgoMapData.Lane)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  waypoints_.Clear();
  ::memset(&road_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&arrow_) -
      reinterpret_cast<char*>(&road_id_)) + sizeof(arrow_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* EgoMapData_Lane::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 road_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          road_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 lane_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          lane_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .sim_msg.EgoMapData.LANE_ARROW arrow = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          set_arrow(static_cast<::sim_msg::EgoMapData_LANE_ARROW>(val));
        } else goto handle_unusual;
        continue;
      // double length = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          length_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // repeated .sim_msg.EgoMapData.WayPoint waypoints = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(add_waypoints(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint8>(ptr) == 42);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool EgoMapData_Lane::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:sim_msg.EgoMapData.Lane)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 road_id = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::uint64, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64>(
                 input, &road_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 lane_id = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (16 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int64, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64>(
                 input, &lane_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .sim_msg.EgoMapData.LANE_ARROW arrow = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (24 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_arrow(static_cast< ::sim_msg::EgoMapData_LANE_ARROW >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double length = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (33 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   double, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .sim_msg.EgoMapData.WayPoint waypoints = 5;
      case 5: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (42 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
                input, add_waypoints()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sim_msg.EgoMapData.Lane)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sim_msg.EgoMapData.Lane)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void EgoMapData_Lane::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sim_msg.EgoMapData.Lane)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 road_id = 1;
  if (this->road_id() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64(1, this->road_id(), output);
  }

  // int64 lane_id = 2;
  if (this->lane_id() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64(2, this->lane_id(), output);
  }

  // .sim_msg.EgoMapData.LANE_ARROW arrow = 3;
  if (this->arrow() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      3, this->arrow(), output);
  }

  // double length = 4;
  if (!(this->length() <= 0 && this->length() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDouble(4, this->length(), output);
  }

  // repeated .sim_msg.EgoMapData.WayPoint waypoints = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->waypoints_size()); i < n; i++) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->waypoints(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sim_msg.EgoMapData.Lane)
}

::PROTOBUF_NAMESPACE_ID::uint8* EgoMapData_Lane::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sim_msg.EgoMapData.Lane)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 road_id = 1;
  if (this->road_id() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->road_id(), target);
  }

  // int64 lane_id = 2;
  if (this->lane_id() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->lane_id(), target);
  }

  // .sim_msg.EgoMapData.LANE_ARROW arrow = 3;
  if (this->arrow() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->arrow(), target);
  }

  // double length = 4;
  if (!(this->length() <= 0 && this->length() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->length(), target);
  }

  // repeated .sim_msg.EgoMapData.WayPoint waypoints = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->waypoints_size()); i < n; i++) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->waypoints(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sim_msg.EgoMapData.Lane)
  return target;
}

size_t EgoMapData_Lane::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sim_msg.EgoMapData.Lane)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .sim_msg.EgoMapData.WayPoint waypoints = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->waypoints_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          this->waypoints(static_cast<int>(i)));
    }
  }

  // uint64 road_id = 1;
  if (this->road_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->road_id());
  }

  // int64 lane_id = 2;
  if (this->lane_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->lane_id());
  }

  // double length = 4;
  if (!(this->length() <= 0 && this->length() >= 0)) {
    total_size += 1 + 8;
  }

  // .sim_msg.EgoMapData.LANE_ARROW arrow = 3;
  if (this->arrow() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->arrow());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EgoMapData_Lane::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sim_msg.EgoMapData.Lane)
  GOOGLE_DCHECK_NE(&from, this);
  const EgoMapData_Lane* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EgoMapData_Lane>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sim_msg.EgoMapData.Lane)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sim_msg.EgoMapData.Lane)
    MergeFrom(*source);
  }
}

void EgoMapData_Lane::MergeFrom(const EgoMapData_Lane& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sim_msg.EgoMapData.Lane)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  waypoints_.MergeFrom(from.waypoints_);
  if (from.road_id() != 0) {
    set_road_id(from.road_id());
  }
  if (from.lane_id() != 0) {
    set_lane_id(from.lane_id());
  }
  if (!(from.length() <= 0 && from.length() >= 0)) {
    set_length(from.length());
  }
  if (from.arrow() != 0) {
    set_arrow(from.arrow());
  }
}

void EgoMapData_Lane::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sim_msg.EgoMapData.Lane)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EgoMapData_Lane::CopyFrom(const EgoMapData_Lane& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sim_msg.EgoMapData.Lane)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EgoMapData_Lane::IsInitialized() const {
  return true;
}

void EgoMapData_Lane::InternalSwap(EgoMapData_Lane* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  CastToBase(&waypoints_)->InternalSwap(CastToBase(&other->waypoints_));
  swap(road_id_, other->road_id_);
  swap(lane_id_, other->lane_id_);
  swap(length_, other->length_);
  swap(arrow_, other->arrow_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EgoMapData_Lane::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void EgoMapData_Link::InitAsDefaultInstance() {
}
class EgoMapData_Link::_Internal {
 public:
};

EgoMapData_Link::EgoMapData_Link()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sim_msg.EgoMapData.Link)
}
EgoMapData_Link::EgoMapData_Link(const EgoMapData_Link& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      waypoints_(from.waypoints_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&link_id_, &from.link_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&length_) -
    reinterpret_cast<char*>(&link_id_)) + sizeof(length_));
  // @@protoc_insertion_point(copy_constructor:sim_msg.EgoMapData.Link)
}

void EgoMapData_Link::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_EgoMapData_Link_egoMapData_2eproto.base);
  ::memset(&link_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&length_) -
      reinterpret_cast<char*>(&link_id_)) + sizeof(length_));
}

EgoMapData_Link::~EgoMapData_Link() {
  // @@protoc_insertion_point(destructor:sim_msg.EgoMapData.Link)
  SharedDtor();
}

void EgoMapData_Link::SharedDtor() {
}

void EgoMapData_Link::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EgoMapData_Link& EgoMapData_Link::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_EgoMapData_Link_egoMapData_2eproto.base);
  return *internal_default_instance();
}


void EgoMapData_Link::Clear() {
// @@protoc_insertion_point(message_clear_start:sim_msg.EgoMapData.Link)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  waypoints_.Clear();
  ::memset(&link_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&length_) -
      reinterpret_cast<char*>(&link_id_)) + sizeof(length_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* EgoMapData_Link::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 link_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          link_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 from_road_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          from_road_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 from_section_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          from_section_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 from_lane_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          from_lane_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 to_road_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          to_road_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 to_section_id = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          to_section_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 to_lane_id = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          to_lane_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 junction_id = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          junction_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double length = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 73)) {
          length_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // repeated .sim_msg.EgoMapData.WayPoint waypoints = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(add_waypoints(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint8>(ptr) == 82);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool EgoMapData_Link::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:sim_msg.EgoMapData.Link)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 link_id = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::uint64, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64>(
                 input, &link_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 from_road_id = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (16 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::uint64, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64>(
                 input, &from_road_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 from_section_id = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (24 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::uint64, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64>(
                 input, &from_section_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 from_lane_id = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (32 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int64, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64>(
                 input, &from_lane_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 to_road_id = 5;
      case 5: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (40 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::uint64, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64>(
                 input, &to_road_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 to_section_id = 6;
      case 6: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (48 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::uint64, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64>(
                 input, &to_section_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 to_lane_id = 7;
      case 7: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (56 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int64, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64>(
                 input, &to_lane_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 junction_id = 8;
      case 8: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (64 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::uint64, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64>(
                 input, &junction_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double length = 9;
      case 9: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (73 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   double, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .sim_msg.EgoMapData.WayPoint waypoints = 10;
      case 10: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (82 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
                input, add_waypoints()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sim_msg.EgoMapData.Link)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sim_msg.EgoMapData.Link)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void EgoMapData_Link::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sim_msg.EgoMapData.Link)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 link_id = 1;
  if (this->link_id() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64(1, this->link_id(), output);
  }

  // uint64 from_road_id = 2;
  if (this->from_road_id() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64(2, this->from_road_id(), output);
  }

  // uint64 from_section_id = 3;
  if (this->from_section_id() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64(3, this->from_section_id(), output);
  }

  // int64 from_lane_id = 4;
  if (this->from_lane_id() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64(4, this->from_lane_id(), output);
  }

  // uint64 to_road_id = 5;
  if (this->to_road_id() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64(5, this->to_road_id(), output);
  }

  // uint64 to_section_id = 6;
  if (this->to_section_id() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64(6, this->to_section_id(), output);
  }

  // int64 to_lane_id = 7;
  if (this->to_lane_id() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64(7, this->to_lane_id(), output);
  }

  // uint64 junction_id = 8;
  if (this->junction_id() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64(8, this->junction_id(), output);
  }

  // double length = 9;
  if (!(this->length() <= 0 && this->length() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDouble(9, this->length(), output);
  }

  // repeated .sim_msg.EgoMapData.WayPoint waypoints = 10;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->waypoints_size()); i < n; i++) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      10,
      this->waypoints(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sim_msg.EgoMapData.Link)
}

::PROTOBUF_NAMESPACE_ID::uint8* EgoMapData_Link::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sim_msg.EgoMapData.Link)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 link_id = 1;
  if (this->link_id() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->link_id(), target);
  }

  // uint64 from_road_id = 2;
  if (this->from_road_id() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(2, this->from_road_id(), target);
  }

  // uint64 from_section_id = 3;
  if (this->from_section_id() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(3, this->from_section_id(), target);
  }

  // int64 from_lane_id = 4;
  if (this->from_lane_id() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(4, this->from_lane_id(), target);
  }

  // uint64 to_road_id = 5;
  if (this->to_road_id() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(5, this->to_road_id(), target);
  }

  // uint64 to_section_id = 6;
  if (this->to_section_id() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(6, this->to_section_id(), target);
  }

  // int64 to_lane_id = 7;
  if (this->to_lane_id() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(7, this->to_lane_id(), target);
  }

  // uint64 junction_id = 8;
  if (this->junction_id() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(8, this->junction_id(), target);
  }

  // double length = 9;
  if (!(this->length() <= 0 && this->length() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(9, this->length(), target);
  }

  // repeated .sim_msg.EgoMapData.WayPoint waypoints = 10;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->waypoints_size()); i < n; i++) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        10, this->waypoints(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sim_msg.EgoMapData.Link)
  return target;
}

size_t EgoMapData_Link::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sim_msg.EgoMapData.Link)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .sim_msg.EgoMapData.WayPoint waypoints = 10;
  {
    unsigned int count = static_cast<unsigned int>(this->waypoints_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          this->waypoints(static_cast<int>(i)));
    }
  }

  // uint64 link_id = 1;
  if (this->link_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->link_id());
  }

  // uint64 from_road_id = 2;
  if (this->from_road_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->from_road_id());
  }

  // uint64 from_section_id = 3;
  if (this->from_section_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->from_section_id());
  }

  // int64 from_lane_id = 4;
  if (this->from_lane_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->from_lane_id());
  }

  // uint64 to_road_id = 5;
  if (this->to_road_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->to_road_id());
  }

  // uint64 to_section_id = 6;
  if (this->to_section_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->to_section_id());
  }

  // int64 to_lane_id = 7;
  if (this->to_lane_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->to_lane_id());
  }

  // uint64 junction_id = 8;
  if (this->junction_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->junction_id());
  }

  // double length = 9;
  if (!(this->length() <= 0 && this->length() >= 0)) {
    total_size += 1 + 8;
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EgoMapData_Link::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sim_msg.EgoMapData.Link)
  GOOGLE_DCHECK_NE(&from, this);
  const EgoMapData_Link* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EgoMapData_Link>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sim_msg.EgoMapData.Link)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sim_msg.EgoMapData.Link)
    MergeFrom(*source);
  }
}

void EgoMapData_Link::MergeFrom(const EgoMapData_Link& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sim_msg.EgoMapData.Link)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  waypoints_.MergeFrom(from.waypoints_);
  if (from.link_id() != 0) {
    set_link_id(from.link_id());
  }
  if (from.from_road_id() != 0) {
    set_from_road_id(from.from_road_id());
  }
  if (from.from_section_id() != 0) {
    set_from_section_id(from.from_section_id());
  }
  if (from.from_lane_id() != 0) {
    set_from_lane_id(from.from_lane_id());
  }
  if (from.to_road_id() != 0) {
    set_to_road_id(from.to_road_id());
  }
  if (from.to_section_id() != 0) {
    set_to_section_id(from.to_section_id());
  }
  if (from.to_lane_id() != 0) {
    set_to_lane_id(from.to_lane_id());
  }
  if (from.junction_id() != 0) {
    set_junction_id(from.junction_id());
  }
  if (!(from.length() <= 0 && from.length() >= 0)) {
    set_length(from.length());
  }
}

void EgoMapData_Link::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sim_msg.EgoMapData.Link)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EgoMapData_Link::CopyFrom(const EgoMapData_Link& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sim_msg.EgoMapData.Link)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EgoMapData_Link::IsInitialized() const {
  return true;
}

void EgoMapData_Link::InternalSwap(EgoMapData_Link* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  CastToBase(&waypoints_)->InternalSwap(CastToBase(&other->waypoints_));
  swap(link_id_, other->link_id_);
  swap(from_road_id_, other->from_road_id_);
  swap(from_section_id_, other->from_section_id_);
  swap(from_lane_id_, other->from_lane_id_);
  swap(to_road_id_, other->to_road_id_);
  swap(to_section_id_, other->to_section_id_);
  swap(to_lane_id_, other->to_lane_id_);
  swap(junction_id_, other->junction_id_);
  swap(length_, other->length_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EgoMapData_Link::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void EgoMapData_RouteNode::InitAsDefaultInstance() {
  ::sim_msg::_EgoMapData_RouteNode_default_instance_._instance.get_mutable()->lane_ = const_cast< ::sim_msg::EgoMapData_Lane*>(
      ::sim_msg::EgoMapData_Lane::internal_default_instance());
  ::sim_msg::_EgoMapData_RouteNode_default_instance_._instance.get_mutable()->link_ = const_cast< ::sim_msg::EgoMapData_Link*>(
      ::sim_msg::EgoMapData_Link::internal_default_instance());
}
class EgoMapData_RouteNode::_Internal {
 public:
  static const ::sim_msg::EgoMapData_Lane& lane(const EgoMapData_RouteNode* msg);
  static const ::sim_msg::EgoMapData_Link& link(const EgoMapData_RouteNode* msg);
};

const ::sim_msg::EgoMapData_Lane&
EgoMapData_RouteNode::_Internal::lane(const EgoMapData_RouteNode* msg) {
  return *msg->lane_;
}
const ::sim_msg::EgoMapData_Link&
EgoMapData_RouteNode::_Internal::link(const EgoMapData_RouteNode* msg) {
  return *msg->link_;
}
EgoMapData_RouteNode::EgoMapData_RouteNode()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sim_msg.EgoMapData.RouteNode)
}
EgoMapData_RouteNode::EgoMapData_RouteNode(const EgoMapData_RouteNode& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_lane()) {
    lane_ = new ::sim_msg::EgoMapData_Lane(*from.lane_);
  } else {
    lane_ = nullptr;
  }
  if (from.has_link()) {
    link_ = new ::sim_msg::EgoMapData_Link(*from.link_);
  } else {
    link_ = nullptr;
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:sim_msg.EgoMapData.RouteNode)
}

void EgoMapData_RouteNode::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_EgoMapData_RouteNode_egoMapData_2eproto.base);
  ::memset(&lane_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&lane_)) + sizeof(type_));
}

EgoMapData_RouteNode::~EgoMapData_RouteNode() {
  // @@protoc_insertion_point(destructor:sim_msg.EgoMapData.RouteNode)
  SharedDtor();
}

void EgoMapData_RouteNode::SharedDtor() {
  if (this != internal_default_instance()) delete lane_;
  if (this != internal_default_instance()) delete link_;
}

void EgoMapData_RouteNode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EgoMapData_RouteNode& EgoMapData_RouteNode::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_EgoMapData_RouteNode_egoMapData_2eproto.base);
  return *internal_default_instance();
}


void EgoMapData_RouteNode::Clear() {
// @@protoc_insertion_point(message_clear_start:sim_msg.EgoMapData.RouteNode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && lane_ != nullptr) {
    delete lane_;
  }
  lane_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && link_ != nullptr) {
    delete link_;
  }
  link_ = nullptr;
  type_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* EgoMapData_RouteNode::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .sim_msg.EgoMapData.RouteNode.Type type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          set_type(static_cast<::sim_msg::EgoMapData_RouteNode_Type>(val));
        } else goto handle_unusual;
        continue;
      // .sim_msg.EgoMapData.Lane lane = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(mutable_lane(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .sim_msg.EgoMapData.Link link = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(mutable_link(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool EgoMapData_RouteNode::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:sim_msg.EgoMapData.RouteNode)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .sim_msg.EgoMapData.RouteNode.Type type = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::sim_msg::EgoMapData_RouteNode_Type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .sim_msg.EgoMapData.Lane lane = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (18 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_lane()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .sim_msg.EgoMapData.Link link = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (26 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_link()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sim_msg.EgoMapData.RouteNode)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sim_msg.EgoMapData.RouteNode)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void EgoMapData_RouteNode::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sim_msg.EgoMapData.RouteNode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .sim_msg.EgoMapData.RouteNode.Type type = 1;
  if (this->type() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // .sim_msg.EgoMapData.Lane lane = 2;
  if (this->has_lane()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, _Internal::lane(this), output);
  }

  // .sim_msg.EgoMapData.Link link = 3;
  if (this->has_link()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, _Internal::link(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sim_msg.EgoMapData.RouteNode)
}

::PROTOBUF_NAMESPACE_ID::uint8* EgoMapData_RouteNode::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sim_msg.EgoMapData.RouteNode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .sim_msg.EgoMapData.RouteNode.Type type = 1;
  if (this->type() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // .sim_msg.EgoMapData.Lane lane = 2;
  if (this->has_lane()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, _Internal::lane(this), target);
  }

  // .sim_msg.EgoMapData.Link link = 3;
  if (this->has_link()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, _Internal::link(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sim_msg.EgoMapData.RouteNode)
  return target;
}

size_t EgoMapData_RouteNode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sim_msg.EgoMapData.RouteNode)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .sim_msg.EgoMapData.Lane lane = 2;
  if (this->has_lane()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *lane_);
  }

  // .sim_msg.EgoMapData.Link link = 3;
  if (this->has_link()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *link_);
  }

  // .sim_msg.EgoMapData.RouteNode.Type type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EgoMapData_RouteNode::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sim_msg.EgoMapData.RouteNode)
  GOOGLE_DCHECK_NE(&from, this);
  const EgoMapData_RouteNode* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EgoMapData_RouteNode>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sim_msg.EgoMapData.RouteNode)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sim_msg.EgoMapData.RouteNode)
    MergeFrom(*source);
  }
}

void EgoMapData_RouteNode::MergeFrom(const EgoMapData_RouteNode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sim_msg.EgoMapData.RouteNode)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_lane()) {
    mutable_lane()->::sim_msg::EgoMapData_Lane::MergeFrom(from.lane());
  }
  if (from.has_link()) {
    mutable_link()->::sim_msg::EgoMapData_Link::MergeFrom(from.link());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void EgoMapData_RouteNode::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sim_msg.EgoMapData.RouteNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EgoMapData_RouteNode::CopyFrom(const EgoMapData_RouteNode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sim_msg.EgoMapData.RouteNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EgoMapData_RouteNode::IsInitialized() const {
  return true;
}

void EgoMapData_RouteNode::InternalSwap(EgoMapData_RouteNode* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(lane_, other->lane_);
  swap(link_, other->link_);
  swap(type_, other->type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EgoMapData_RouteNode::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void EgoMapData::InitAsDefaultInstance() {
  ::sim_msg::_EgoMapData_default_instance_._instance.get_mutable()->header_ = const_cast< ::sim_msg::Header*>(
      ::sim_msg::Header::internal_default_instance());
}
class EgoMapData::_Internal {
 public:
  static const ::sim_msg::Header& header(const EgoMapData* msg);
};

const ::sim_msg::Header&
EgoMapData::_Internal::header(const EgoMapData* msg) {
  return *msg->header_;
}
void EgoMapData::clear_header() {
  if (GetArenaNoVirtual() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
EgoMapData::EgoMapData()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sim_msg.EgoMapData)
}
EgoMapData::EgoMapData(const EgoMapData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      route_nodes_(from.route_nodes_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_header()) {
    header_ = new ::sim_msg::Header(*from.header_);
  } else {
    header_ = nullptr;
  }
  ::memcpy(&s_, &from.s_,
    static_cast<size_t>(reinterpret_cast<char*>(&on_link_) -
    reinterpret_cast<char*>(&s_)) + sizeof(on_link_));
  // @@protoc_insertion_point(copy_constructor:sim_msg.EgoMapData)
}

void EgoMapData::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_EgoMapData_egoMapData_2eproto.base);
  ::memset(&header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&on_link_) -
      reinterpret_cast<char*>(&header_)) + sizeof(on_link_));
}

EgoMapData::~EgoMapData() {
  // @@protoc_insertion_point(destructor:sim_msg.EgoMapData)
  SharedDtor();
}

void EgoMapData::SharedDtor() {
  if (this != internal_default_instance()) delete header_;
}

void EgoMapData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EgoMapData& EgoMapData::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_EgoMapData_egoMapData_2eproto.base);
  return *internal_default_instance();
}


void EgoMapData::Clear() {
// @@protoc_insertion_point(message_clear_start:sim_msg.EgoMapData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  route_nodes_.Clear();
  if (GetArenaNoVirtual() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
  ::memset(&s_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&on_link_) -
      reinterpret_cast<char*>(&s_)) + sizeof(on_link_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* EgoMapData::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .sim_msg.Header header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(mutable_header(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .sim_msg.EgoMapData.RouteNode route_nodes = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(add_route_nodes(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint8>(ptr) == 18);
        } else goto handle_unusual;
        continue;
      // bool on_lane = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          on_lane_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool on_link = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          on_link_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double s = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 41)) {
          s_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double l = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          l_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double yaw = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 57)) {
          yaw_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double dis_to_end = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 65)) {
          dis_to_end_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool EgoMapData::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:sim_msg.EgoMapData)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .sim_msg.Header header = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (10 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .sim_msg.EgoMapData.RouteNode route_nodes = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (18 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
                input, add_route_nodes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool on_lane = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (24 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   bool, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BOOL>(
                 input, &on_lane_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool on_link = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (32 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   bool, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BOOL>(
                 input, &on_link_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double s = 5;
      case 5: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (41 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   double, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &s_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double l = 6;
      case 6: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (49 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   double, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &l_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double yaw = 7;
      case 7: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (57 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   double, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &yaw_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double dis_to_end = 8;
      case 8: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (65 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   double, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dis_to_end_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sim_msg.EgoMapData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sim_msg.EgoMapData)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void EgoMapData::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sim_msg.EgoMapData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .sim_msg.Header header = 1;
  if (this->has_header()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, _Internal::header(this), output);
  }

  // repeated .sim_msg.EgoMapData.RouteNode route_nodes = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->route_nodes_size()); i < n; i++) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->route_nodes(static_cast<int>(i)),
      output);
  }

  // bool on_lane = 3;
  if (this->on_lane() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBool(3, this->on_lane(), output);
  }

  // bool on_link = 4;
  if (this->on_link() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBool(4, this->on_link(), output);
  }

  // double s = 5;
  if (!(this->s() <= 0 && this->s() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDouble(5, this->s(), output);
  }

  // double l = 6;
  if (!(this->l() <= 0 && this->l() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDouble(6, this->l(), output);
  }

  // double yaw = 7;
  if (!(this->yaw() <= 0 && this->yaw() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDouble(7, this->yaw(), output);
  }

  // double dis_to_end = 8;
  if (!(this->dis_to_end() <= 0 && this->dis_to_end() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDouble(8, this->dis_to_end(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sim_msg.EgoMapData)
}

::PROTOBUF_NAMESPACE_ID::uint8* EgoMapData::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sim_msg.EgoMapData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .sim_msg.Header header = 1;
  if (this->has_header()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, _Internal::header(this), target);
  }

  // repeated .sim_msg.EgoMapData.RouteNode route_nodes = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->route_nodes_size()); i < n; i++) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->route_nodes(static_cast<int>(i)), target);
  }

  // bool on_lane = 3;
  if (this->on_lane() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->on_lane(), target);
  }

  // bool on_link = 4;
  if (this->on_link() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->on_link(), target);
  }

  // double s = 5;
  if (!(this->s() <= 0 && this->s() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(5, this->s(), target);
  }

  // double l = 6;
  if (!(this->l() <= 0 && this->l() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->l(), target);
  }

  // double yaw = 7;
  if (!(this->yaw() <= 0 && this->yaw() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(7, this->yaw(), target);
  }

  // double dis_to_end = 8;
  if (!(this->dis_to_end() <= 0 && this->dis_to_end() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(8, this->dis_to_end(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sim_msg.EgoMapData)
  return target;
}

size_t EgoMapData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sim_msg.EgoMapData)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .sim_msg.EgoMapData.RouteNode route_nodes = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->route_nodes_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          this->route_nodes(static_cast<int>(i)));
    }
  }

  // .sim_msg.Header header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *header_);
  }

  // double s = 5;
  if (!(this->s() <= 0 && this->s() >= 0)) {
    total_size += 1 + 8;
  }

  // double l = 6;
  if (!(this->l() <= 0 && this->l() >= 0)) {
    total_size += 1 + 8;
  }

  // double yaw = 7;
  if (!(this->yaw() <= 0 && this->yaw() >= 0)) {
    total_size += 1 + 8;
  }

  // double dis_to_end = 8;
  if (!(this->dis_to_end() <= 0 && this->dis_to_end() >= 0)) {
    total_size += 1 + 8;
  }

  // bool on_lane = 3;
  if (this->on_lane() != 0) {
    total_size += 1 + 1;
  }

  // bool on_link = 4;
  if (this->on_link() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EgoMapData::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sim_msg.EgoMapData)
  GOOGLE_DCHECK_NE(&from, this);
  const EgoMapData* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EgoMapData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sim_msg.EgoMapData)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sim_msg.EgoMapData)
    MergeFrom(*source);
  }
}

void EgoMapData::MergeFrom(const EgoMapData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sim_msg.EgoMapData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  route_nodes_.MergeFrom(from.route_nodes_);
  if (from.has_header()) {
    mutable_header()->::sim_msg::Header::MergeFrom(from.header());
  }
  if (!(from.s() <= 0 && from.s() >= 0)) {
    set_s(from.s());
  }
  if (!(from.l() <= 0 && from.l() >= 0)) {
    set_l(from.l());
  }
  if (!(from.yaw() <= 0 && from.yaw() >= 0)) {
    set_yaw(from.yaw());
  }
  if (!(from.dis_to_end() <= 0 && from.dis_to_end() >= 0)) {
    set_dis_to_end(from.dis_to_end());
  }
  if (from.on_lane() != 0) {
    set_on_lane(from.on_lane());
  }
  if (from.on_link() != 0) {
    set_on_link(from.on_link());
  }
}

void EgoMapData::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sim_msg.EgoMapData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EgoMapData::CopyFrom(const EgoMapData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sim_msg.EgoMapData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EgoMapData::IsInitialized() const {
  return true;
}

void EgoMapData::InternalSwap(EgoMapData* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  CastToBase(&route_nodes_)->InternalSwap(CastToBase(&other->route_nodes_));
  swap(header_, other->header_);
  swap(s_, other->s_);
  swap(l_, other->l_);
  swap(yaw_, other->yaw_);
  swap(dis_to_end_, other->dis_to_end_);
  swap(on_lane_, other->on_lane_);
  swap(on_link_, other->on_link_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EgoMapData::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace sim_msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sim_msg::EgoMapData_WayPoint* Arena::CreateMaybeMessage< ::sim_msg::EgoMapData_WayPoint >(Arena* arena) {
  return Arena::CreateInternal< ::sim_msg::EgoMapData_WayPoint >(arena);
}
template<> PROTOBUF_NOINLINE ::sim_msg::EgoMapData_Lane* Arena::CreateMaybeMessage< ::sim_msg::EgoMapData_Lane >(Arena* arena) {
  return Arena::CreateInternal< ::sim_msg::EgoMapData_Lane >(arena);
}
template<> PROTOBUF_NOINLINE ::sim_msg::EgoMapData_Link* Arena::CreateMaybeMessage< ::sim_msg::EgoMapData_Link >(Arena* arena) {
  return Arena::CreateInternal< ::sim_msg::EgoMapData_Link >(arena);
}
template<> PROTOBUF_NOINLINE ::sim_msg::EgoMapData_RouteNode* Arena::CreateMaybeMessage< ::sim_msg::EgoMapData_RouteNode >(Arena* arena) {
  return Arena::CreateInternal< ::sim_msg::EgoMapData_RouteNode >(arena);
}
template<> PROTOBUF_NOINLINE ::sim_msg::EgoMapData* Arena::CreateMaybeMessage< ::sim_msg::EgoMapData >(Arena* arena) {
  return Arena::CreateInternal< ::sim_msg::EgoMapData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
