// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osi_trafficcommandupdate.proto

#include "osi_trafficcommandupdate.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_osi_5fcommon_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Identifier_osi_5fcommon_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_osi_5fversion_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_InterfaceVersion_osi_5fversion_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_osi_5fcommon_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Timestamp_osi_5fcommon_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_osi_5ftrafficcommandupdate_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_TrafficCommandUpdate_DismissedAction_osi_5ftrafficcommandupdate_2eproto;
namespace osi3 {
class TrafficCommandUpdate_DismissedActionDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TrafficCommandUpdate_DismissedAction> _instance;
} _TrafficCommandUpdate_DismissedAction_default_instance_;
class TrafficCommandUpdateDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TrafficCommandUpdate> _instance;
} _TrafficCommandUpdate_default_instance_;
}  // namespace osi3
static void InitDefaultsscc_info_TrafficCommandUpdate_osi_5ftrafficcommandupdate_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::osi3::_TrafficCommandUpdate_default_instance_;
    new (ptr) ::osi3::TrafficCommandUpdate();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::osi3::TrafficCommandUpdate::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<4> scc_info_TrafficCommandUpdate_osi_5ftrafficcommandupdate_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 4, InitDefaultsscc_info_TrafficCommandUpdate_osi_5ftrafficcommandupdate_2eproto}, {
      &scc_info_InterfaceVersion_osi_5fversion_2eproto.base,
      &scc_info_Timestamp_osi_5fcommon_2eproto.base,
      &scc_info_Identifier_osi_5fcommon_2eproto.base,
      &scc_info_TrafficCommandUpdate_DismissedAction_osi_5ftrafficcommandupdate_2eproto.base,}};

static void InitDefaultsscc_info_TrafficCommandUpdate_DismissedAction_osi_5ftrafficcommandupdate_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::osi3::_TrafficCommandUpdate_DismissedAction_default_instance_;
    new (ptr) ::osi3::TrafficCommandUpdate_DismissedAction();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::osi3::TrafficCommandUpdate_DismissedAction::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_TrafficCommandUpdate_DismissedAction_osi_5ftrafficcommandupdate_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsscc_info_TrafficCommandUpdate_DismissedAction_osi_5ftrafficcommandupdate_2eproto}, {
      &scc_info_Identifier_osi_5fcommon_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_osi_5ftrafficcommandupdate_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_osi_5ftrafficcommandupdate_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_osi_5ftrafficcommandupdate_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_osi_5ftrafficcommandupdate_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::osi3::TrafficCommandUpdate_DismissedAction, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::osi3::TrafficCommandUpdate_DismissedAction, dismissed_action_id_),
  PROTOBUF_FIELD_OFFSET(::osi3::TrafficCommandUpdate_DismissedAction, failure_reason_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::osi3::TrafficCommandUpdate, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::osi3::TrafficCommandUpdate, version_),
  PROTOBUF_FIELD_OFFSET(::osi3::TrafficCommandUpdate, timestamp_),
  PROTOBUF_FIELD_OFFSET(::osi3::TrafficCommandUpdate, traffic_participant_id_),
  PROTOBUF_FIELD_OFFSET(::osi3::TrafficCommandUpdate, dismissed_action_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::osi3::TrafficCommandUpdate_DismissedAction)},
  { 7, -1, sizeof(::osi3::TrafficCommandUpdate)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::osi3::_TrafficCommandUpdate_DismissedAction_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::osi3::_TrafficCommandUpdate_default_instance_),
};

const char descriptor_table_protodef_osi_5ftrafficcommandupdate_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036osi_trafficcommandupdate.proto\022\004osi3\032\021"
  "osi_version.proto\032\020osi_common.proto\"\265\002\n\024"
  "TrafficCommandUpdate\022\'\n\007version\030\001 \001(\0132\026."
  "osi3.InterfaceVersion\022\"\n\ttimestamp\030\002 \001(\013"
  "2\017.osi3.Timestamp\0220\n\026traffic_participant"
  "_id\030\003 \001(\0132\020.osi3.Identifier\022D\n\020dismissed"
  "_action\030\004 \003(\0132*.osi3.TrafficCommandUpdat"
  "e.DismissedAction\032X\n\017DismissedAction\022-\n\023"
  "dismissed_action_id\030\001 \001(\0132\020.osi3.Identif"
  "ier\022\026\n\016failure_reason\030\002 \001(\tB\002H\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_osi_5ftrafficcommandupdate_2eproto_deps[2] = {
  &::descriptor_table_osi_5fcommon_2eproto,
  &::descriptor_table_osi_5fversion_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_osi_5ftrafficcommandupdate_2eproto_sccs[2] = {
  &scc_info_TrafficCommandUpdate_osi_5ftrafficcommandupdate_2eproto.base,
  &scc_info_TrafficCommandUpdate_DismissedAction_osi_5ftrafficcommandupdate_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_osi_5ftrafficcommandupdate_2eproto_once;
static bool descriptor_table_osi_5ftrafficcommandupdate_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_osi_5ftrafficcommandupdate_2eproto = {
  &descriptor_table_osi_5ftrafficcommandupdate_2eproto_initialized, descriptor_table_protodef_osi_5ftrafficcommandupdate_2eproto, "osi_trafficcommandupdate.proto", 399,
  &descriptor_table_osi_5ftrafficcommandupdate_2eproto_once, descriptor_table_osi_5ftrafficcommandupdate_2eproto_sccs, descriptor_table_osi_5ftrafficcommandupdate_2eproto_deps, 2, 2,
  schemas, file_default_instances, TableStruct_osi_5ftrafficcommandupdate_2eproto::offsets,
  file_level_metadata_osi_5ftrafficcommandupdate_2eproto, 2, file_level_enum_descriptors_osi_5ftrafficcommandupdate_2eproto, file_level_service_descriptors_osi_5ftrafficcommandupdate_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_osi_5ftrafficcommandupdate_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_osi_5ftrafficcommandupdate_2eproto), true);
namespace osi3 {

// ===================================================================

void TrafficCommandUpdate_DismissedAction::InitAsDefaultInstance() {
  ::osi3::_TrafficCommandUpdate_DismissedAction_default_instance_._instance.get_mutable()->dismissed_action_id_ = const_cast< ::osi3::Identifier*>(
      ::osi3::Identifier::internal_default_instance());
}
class TrafficCommandUpdate_DismissedAction::_Internal {
 public:
  static const ::osi3::Identifier& dismissed_action_id(const TrafficCommandUpdate_DismissedAction* msg);
};

const ::osi3::Identifier&
TrafficCommandUpdate_DismissedAction::_Internal::dismissed_action_id(const TrafficCommandUpdate_DismissedAction* msg) {
  return *msg->dismissed_action_id_;
}
void TrafficCommandUpdate_DismissedAction::clear_dismissed_action_id() {
  if (GetArenaNoVirtual() == nullptr && dismissed_action_id_ != nullptr) {
    delete dismissed_action_id_;
  }
  dismissed_action_id_ = nullptr;
}
TrafficCommandUpdate_DismissedAction::TrafficCommandUpdate_DismissedAction()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:osi3.TrafficCommandUpdate.DismissedAction)
}
TrafficCommandUpdate_DismissedAction::TrafficCommandUpdate_DismissedAction(const TrafficCommandUpdate_DismissedAction& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  failure_reason_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from.failure_reason().empty()) {
    failure_reason_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.failure_reason_);
  }
  if (from.has_dismissed_action_id()) {
    dismissed_action_id_ = new ::osi3::Identifier(*from.dismissed_action_id_);
  } else {
    dismissed_action_id_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:osi3.TrafficCommandUpdate.DismissedAction)
}

void TrafficCommandUpdate_DismissedAction::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TrafficCommandUpdate_DismissedAction_osi_5ftrafficcommandupdate_2eproto.base);
  failure_reason_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  dismissed_action_id_ = nullptr;
}

TrafficCommandUpdate_DismissedAction::~TrafficCommandUpdate_DismissedAction() {
  // @@protoc_insertion_point(destructor:osi3.TrafficCommandUpdate.DismissedAction)
  SharedDtor();
}

void TrafficCommandUpdate_DismissedAction::SharedDtor() {
  failure_reason_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete dismissed_action_id_;
}

void TrafficCommandUpdate_DismissedAction::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TrafficCommandUpdate_DismissedAction& TrafficCommandUpdate_DismissedAction::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TrafficCommandUpdate_DismissedAction_osi_5ftrafficcommandupdate_2eproto.base);
  return *internal_default_instance();
}


void TrafficCommandUpdate_DismissedAction::Clear() {
// @@protoc_insertion_point(message_clear_start:osi3.TrafficCommandUpdate.DismissedAction)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  failure_reason_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == nullptr && dismissed_action_id_ != nullptr) {
    delete dismissed_action_id_;
  }
  dismissed_action_id_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* TrafficCommandUpdate_DismissedAction::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .osi3.Identifier dismissed_action_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(mutable_dismissed_action_id(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string failure_reason = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(mutable_failure_reason(), ptr, ctx, "osi3.TrafficCommandUpdate.DismissedAction.failure_reason");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool TrafficCommandUpdate_DismissedAction::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:osi3.TrafficCommandUpdate.DismissedAction)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .osi3.Identifier dismissed_action_id = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (10 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_dismissed_action_id()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string failure_reason = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (18 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadString(
                input, this->mutable_failure_reason()));
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
            this->failure_reason().data(), static_cast<int>(this->failure_reason().length()),
            ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE,
            "osi3.TrafficCommandUpdate.DismissedAction.failure_reason"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:osi3.TrafficCommandUpdate.DismissedAction)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:osi3.TrafficCommandUpdate.DismissedAction)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void TrafficCommandUpdate_DismissedAction::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:osi3.TrafficCommandUpdate.DismissedAction)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .osi3.Identifier dismissed_action_id = 1;
  if (this->has_dismissed_action_id()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, _Internal::dismissed_action_id(this), output);
  }

  // string failure_reason = 2;
  if (this->failure_reason().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->failure_reason().data(), static_cast<int>(this->failure_reason().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "osi3.TrafficCommandUpdate.DismissedAction.failure_reason");
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->failure_reason(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:osi3.TrafficCommandUpdate.DismissedAction)
}

::PROTOBUF_NAMESPACE_ID::uint8* TrafficCommandUpdate_DismissedAction::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:osi3.TrafficCommandUpdate.DismissedAction)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .osi3.Identifier dismissed_action_id = 1;
  if (this->has_dismissed_action_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, _Internal::dismissed_action_id(this), target);
  }

  // string failure_reason = 2;
  if (this->failure_reason().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->failure_reason().data(), static_cast<int>(this->failure_reason().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "osi3.TrafficCommandUpdate.DismissedAction.failure_reason");
    target =
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteStringToArray(
        2, this->failure_reason(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:osi3.TrafficCommandUpdate.DismissedAction)
  return target;
}

size_t TrafficCommandUpdate_DismissedAction::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:osi3.TrafficCommandUpdate.DismissedAction)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string failure_reason = 2;
  if (this->failure_reason().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->failure_reason());
  }

  // .osi3.Identifier dismissed_action_id = 1;
  if (this->has_dismissed_action_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *dismissed_action_id_);
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TrafficCommandUpdate_DismissedAction::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:osi3.TrafficCommandUpdate.DismissedAction)
  GOOGLE_DCHECK_NE(&from, this);
  const TrafficCommandUpdate_DismissedAction* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TrafficCommandUpdate_DismissedAction>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:osi3.TrafficCommandUpdate.DismissedAction)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:osi3.TrafficCommandUpdate.DismissedAction)
    MergeFrom(*source);
  }
}

void TrafficCommandUpdate_DismissedAction::MergeFrom(const TrafficCommandUpdate_DismissedAction& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:osi3.TrafficCommandUpdate.DismissedAction)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.failure_reason().size() > 0) {

    failure_reason_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.failure_reason_);
  }
  if (from.has_dismissed_action_id()) {
    mutable_dismissed_action_id()->::osi3::Identifier::MergeFrom(from.dismissed_action_id());
  }
}

void TrafficCommandUpdate_DismissedAction::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:osi3.TrafficCommandUpdate.DismissedAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TrafficCommandUpdate_DismissedAction::CopyFrom(const TrafficCommandUpdate_DismissedAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:osi3.TrafficCommandUpdate.DismissedAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrafficCommandUpdate_DismissedAction::IsInitialized() const {
  return true;
}

void TrafficCommandUpdate_DismissedAction::InternalSwap(TrafficCommandUpdate_DismissedAction* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  failure_reason_.Swap(&other->failure_reason_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(dismissed_action_id_, other->dismissed_action_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TrafficCommandUpdate_DismissedAction::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void TrafficCommandUpdate::InitAsDefaultInstance() {
  ::osi3::_TrafficCommandUpdate_default_instance_._instance.get_mutable()->version_ = const_cast< ::osi3::InterfaceVersion*>(
      ::osi3::InterfaceVersion::internal_default_instance());
  ::osi3::_TrafficCommandUpdate_default_instance_._instance.get_mutable()->timestamp_ = const_cast< ::osi3::Timestamp*>(
      ::osi3::Timestamp::internal_default_instance());
  ::osi3::_TrafficCommandUpdate_default_instance_._instance.get_mutable()->traffic_participant_id_ = const_cast< ::osi3::Identifier*>(
      ::osi3::Identifier::internal_default_instance());
}
class TrafficCommandUpdate::_Internal {
 public:
  static const ::osi3::InterfaceVersion& version(const TrafficCommandUpdate* msg);
  static const ::osi3::Timestamp& timestamp(const TrafficCommandUpdate* msg);
  static const ::osi3::Identifier& traffic_participant_id(const TrafficCommandUpdate* msg);
};

const ::osi3::InterfaceVersion&
TrafficCommandUpdate::_Internal::version(const TrafficCommandUpdate* msg) {
  return *msg->version_;
}
const ::osi3::Timestamp&
TrafficCommandUpdate::_Internal::timestamp(const TrafficCommandUpdate* msg) {
  return *msg->timestamp_;
}
const ::osi3::Identifier&
TrafficCommandUpdate::_Internal::traffic_participant_id(const TrafficCommandUpdate* msg) {
  return *msg->traffic_participant_id_;
}
void TrafficCommandUpdate::clear_version() {
  if (GetArenaNoVirtual() == nullptr && version_ != nullptr) {
    delete version_;
  }
  version_ = nullptr;
}
void TrafficCommandUpdate::clear_timestamp() {
  if (GetArenaNoVirtual() == nullptr && timestamp_ != nullptr) {
    delete timestamp_;
  }
  timestamp_ = nullptr;
}
void TrafficCommandUpdate::clear_traffic_participant_id() {
  if (GetArenaNoVirtual() == nullptr && traffic_participant_id_ != nullptr) {
    delete traffic_participant_id_;
  }
  traffic_participant_id_ = nullptr;
}
TrafficCommandUpdate::TrafficCommandUpdate()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:osi3.TrafficCommandUpdate)
}
TrafficCommandUpdate::TrafficCommandUpdate(const TrafficCommandUpdate& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      dismissed_action_(from.dismissed_action_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_version()) {
    version_ = new ::osi3::InterfaceVersion(*from.version_);
  } else {
    version_ = nullptr;
  }
  if (from.has_timestamp()) {
    timestamp_ = new ::osi3::Timestamp(*from.timestamp_);
  } else {
    timestamp_ = nullptr;
  }
  if (from.has_traffic_participant_id()) {
    traffic_participant_id_ = new ::osi3::Identifier(*from.traffic_participant_id_);
  } else {
    traffic_participant_id_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:osi3.TrafficCommandUpdate)
}

void TrafficCommandUpdate::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TrafficCommandUpdate_osi_5ftrafficcommandupdate_2eproto.base);
  ::memset(&version_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&traffic_participant_id_) -
      reinterpret_cast<char*>(&version_)) + sizeof(traffic_participant_id_));
}

TrafficCommandUpdate::~TrafficCommandUpdate() {
  // @@protoc_insertion_point(destructor:osi3.TrafficCommandUpdate)
  SharedDtor();
}

void TrafficCommandUpdate::SharedDtor() {
  if (this != internal_default_instance()) delete version_;
  if (this != internal_default_instance()) delete timestamp_;
  if (this != internal_default_instance()) delete traffic_participant_id_;
}

void TrafficCommandUpdate::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TrafficCommandUpdate& TrafficCommandUpdate::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TrafficCommandUpdate_osi_5ftrafficcommandupdate_2eproto.base);
  return *internal_default_instance();
}


void TrafficCommandUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:osi3.TrafficCommandUpdate)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  dismissed_action_.Clear();
  if (GetArenaNoVirtual() == nullptr && version_ != nullptr) {
    delete version_;
  }
  version_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && timestamp_ != nullptr) {
    delete timestamp_;
  }
  timestamp_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && traffic_participant_id_ != nullptr) {
    delete traffic_participant_id_;
  }
  traffic_participant_id_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* TrafficCommandUpdate::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .osi3.InterfaceVersion version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(mutable_version(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .osi3.Timestamp timestamp = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(mutable_timestamp(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .osi3.Identifier traffic_participant_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(mutable_traffic_participant_id(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .osi3.TrafficCommandUpdate.DismissedAction dismissed_action = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(add_dismissed_action(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint8>(ptr) == 34);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool TrafficCommandUpdate::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:osi3.TrafficCommandUpdate)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .osi3.InterfaceVersion version = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (10 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_version()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .osi3.Timestamp timestamp = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (18 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_timestamp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .osi3.Identifier traffic_participant_id = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (26 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
               input, mutable_traffic_participant_id()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .osi3.TrafficCommandUpdate.DismissedAction dismissed_action = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (34 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadMessage(
                input, add_dismissed_action()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:osi3.TrafficCommandUpdate)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:osi3.TrafficCommandUpdate)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void TrafficCommandUpdate::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:osi3.TrafficCommandUpdate)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .osi3.InterfaceVersion version = 1;
  if (this->has_version()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, _Internal::version(this), output);
  }

  // .osi3.Timestamp timestamp = 2;
  if (this->has_timestamp()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, _Internal::timestamp(this), output);
  }

  // .osi3.Identifier traffic_participant_id = 3;
  if (this->has_traffic_participant_id()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, _Internal::traffic_participant_id(this), output);
  }

  // repeated .osi3.TrafficCommandUpdate.DismissedAction dismissed_action = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->dismissed_action_size()); i < n; i++) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteMessageMaybeToArray(
      4,
      this->dismissed_action(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:osi3.TrafficCommandUpdate)
}

::PROTOBUF_NAMESPACE_ID::uint8* TrafficCommandUpdate::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:osi3.TrafficCommandUpdate)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .osi3.InterfaceVersion version = 1;
  if (this->has_version()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, _Internal::version(this), target);
  }

  // .osi3.Timestamp timestamp = 2;
  if (this->has_timestamp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, _Internal::timestamp(this), target);
  }

  // .osi3.Identifier traffic_participant_id = 3;
  if (this->has_traffic_participant_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, _Internal::traffic_participant_id(this), target);
  }

  // repeated .osi3.TrafficCommandUpdate.DismissedAction dismissed_action = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->dismissed_action_size()); i < n; i++) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->dismissed_action(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:osi3.TrafficCommandUpdate)
  return target;
}

size_t TrafficCommandUpdate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:osi3.TrafficCommandUpdate)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .osi3.TrafficCommandUpdate.DismissedAction dismissed_action = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->dismissed_action_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          this->dismissed_action(static_cast<int>(i)));
    }
  }

  // .osi3.InterfaceVersion version = 1;
  if (this->has_version()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *version_);
  }

  // .osi3.Timestamp timestamp = 2;
  if (this->has_timestamp()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *timestamp_);
  }

  // .osi3.Identifier traffic_participant_id = 3;
  if (this->has_traffic_participant_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *traffic_participant_id_);
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TrafficCommandUpdate::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:osi3.TrafficCommandUpdate)
  GOOGLE_DCHECK_NE(&from, this);
  const TrafficCommandUpdate* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TrafficCommandUpdate>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:osi3.TrafficCommandUpdate)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:osi3.TrafficCommandUpdate)
    MergeFrom(*source);
  }
}

void TrafficCommandUpdate::MergeFrom(const TrafficCommandUpdate& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:osi3.TrafficCommandUpdate)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  dismissed_action_.MergeFrom(from.dismissed_action_);
  if (from.has_version()) {
    mutable_version()->::osi3::InterfaceVersion::MergeFrom(from.version());
  }
  if (from.has_timestamp()) {
    mutable_timestamp()->::osi3::Timestamp::MergeFrom(from.timestamp());
  }
  if (from.has_traffic_participant_id()) {
    mutable_traffic_participant_id()->::osi3::Identifier::MergeFrom(from.traffic_participant_id());
  }
}

void TrafficCommandUpdate::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:osi3.TrafficCommandUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TrafficCommandUpdate::CopyFrom(const TrafficCommandUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:osi3.TrafficCommandUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrafficCommandUpdate::IsInitialized() const {
  return true;
}

void TrafficCommandUpdate::InternalSwap(TrafficCommandUpdate* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  CastToBase(&dismissed_action_)->InternalSwap(CastToBase(&other->dismissed_action_));
  swap(version_, other->version_);
  swap(timestamp_, other->timestamp_);
  swap(traffic_participant_id_, other->traffic_participant_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TrafficCommandUpdate::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace osi3
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::osi3::TrafficCommandUpdate_DismissedAction* Arena::CreateMaybeMessage< ::osi3::TrafficCommandUpdate_DismissedAction >(Arena* arena) {
  return Arena::CreateInternal< ::osi3::TrafficCommandUpdate_DismissedAction >(arena);
}
template<> PROTOBUF_NOINLINE ::osi3::TrafficCommandUpdate* Arena::CreateMaybeMessage< ::osi3::TrafficCommandUpdate >(Arena* arena) {
  return Arena::CreateInternal< ::osi3::TrafficCommandUpdate >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
