// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osi_trafficcommandupdate.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_osi_5ftrafficcommandupdate_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_osi_5ftrafficcommandupdate_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "osi_version.pb.h"
#include "osi_common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_osi_5ftrafficcommandupdate_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_osi_5ftrafficcommandupdate_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_osi_5ftrafficcommandupdate_2eproto;
namespace osi3 {
class TrafficCommandUpdate;
class TrafficCommandUpdateDefaultTypeInternal;
extern TrafficCommandUpdateDefaultTypeInternal _TrafficCommandUpdate_default_instance_;
class TrafficCommandUpdate_DismissedAction;
class TrafficCommandUpdate_DismissedActionDefaultTypeInternal;
extern TrafficCommandUpdate_DismissedActionDefaultTypeInternal _TrafficCommandUpdate_DismissedAction_default_instance_;
}  // namespace osi3
PROTOBUF_NAMESPACE_OPEN
template<> ::osi3::TrafficCommandUpdate* Arena::CreateMaybeMessage<::osi3::TrafficCommandUpdate>(Arena*);
template<> ::osi3::TrafficCommandUpdate_DismissedAction* Arena::CreateMaybeMessage<::osi3::TrafficCommandUpdate_DismissedAction>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace osi3 {

// ===================================================================

class TrafficCommandUpdate_DismissedAction :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:osi3.TrafficCommandUpdate.DismissedAction) */ {
 public:
  TrafficCommandUpdate_DismissedAction();
  virtual ~TrafficCommandUpdate_DismissedAction();

  TrafficCommandUpdate_DismissedAction(const TrafficCommandUpdate_DismissedAction& from);
  TrafficCommandUpdate_DismissedAction(TrafficCommandUpdate_DismissedAction&& from) noexcept
    : TrafficCommandUpdate_DismissedAction() {
    *this = ::std::move(from);
  }

  inline TrafficCommandUpdate_DismissedAction& operator=(const TrafficCommandUpdate_DismissedAction& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrafficCommandUpdate_DismissedAction& operator=(TrafficCommandUpdate_DismissedAction&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TrafficCommandUpdate_DismissedAction& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TrafficCommandUpdate_DismissedAction* internal_default_instance() {
    return reinterpret_cast<const TrafficCommandUpdate_DismissedAction*>(
               &_TrafficCommandUpdate_DismissedAction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TrafficCommandUpdate_DismissedAction& a, TrafficCommandUpdate_DismissedAction& b) {
    a.Swap(&b);
  }
  inline void Swap(TrafficCommandUpdate_DismissedAction* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TrafficCommandUpdate_DismissedAction* New() const final {
    return CreateMaybeMessage<TrafficCommandUpdate_DismissedAction>(nullptr);
  }

  TrafficCommandUpdate_DismissedAction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TrafficCommandUpdate_DismissedAction>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TrafficCommandUpdate_DismissedAction& from);
  void MergeFrom(const TrafficCommandUpdate_DismissedAction& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrafficCommandUpdate_DismissedAction* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "osi3.TrafficCommandUpdate.DismissedAction";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_osi_5ftrafficcommandupdate_2eproto);
    return ::descriptor_table_osi_5ftrafficcommandupdate_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFailureReasonFieldNumber = 2,
    kDismissedActionIdFieldNumber = 1,
  };
  // string failure_reason = 2;
  void clear_failure_reason();
  const std::string& failure_reason() const;
  void set_failure_reason(const std::string& value);
  void set_failure_reason(std::string&& value);
  void set_failure_reason(const char* value);
  void set_failure_reason(const char* value, size_t size);
  std::string* mutable_failure_reason();
  std::string* release_failure_reason();
  void set_allocated_failure_reason(std::string* failure_reason);

  // .osi3.Identifier dismissed_action_id = 1;
  bool has_dismissed_action_id() const;
  void clear_dismissed_action_id();
  const ::osi3::Identifier& dismissed_action_id() const;
  ::osi3::Identifier* release_dismissed_action_id();
  ::osi3::Identifier* mutable_dismissed_action_id();
  void set_allocated_dismissed_action_id(::osi3::Identifier* dismissed_action_id);

  // @@protoc_insertion_point(class_scope:osi3.TrafficCommandUpdate.DismissedAction)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr failure_reason_;
  ::osi3::Identifier* dismissed_action_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_osi_5ftrafficcommandupdate_2eproto;
};
// -------------------------------------------------------------------

class TrafficCommandUpdate :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:osi3.TrafficCommandUpdate) */ {
 public:
  TrafficCommandUpdate();
  virtual ~TrafficCommandUpdate();

  TrafficCommandUpdate(const TrafficCommandUpdate& from);
  TrafficCommandUpdate(TrafficCommandUpdate&& from) noexcept
    : TrafficCommandUpdate() {
    *this = ::std::move(from);
  }

  inline TrafficCommandUpdate& operator=(const TrafficCommandUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrafficCommandUpdate& operator=(TrafficCommandUpdate&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TrafficCommandUpdate& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TrafficCommandUpdate* internal_default_instance() {
    return reinterpret_cast<const TrafficCommandUpdate*>(
               &_TrafficCommandUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TrafficCommandUpdate& a, TrafficCommandUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(TrafficCommandUpdate* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TrafficCommandUpdate* New() const final {
    return CreateMaybeMessage<TrafficCommandUpdate>(nullptr);
  }

  TrafficCommandUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TrafficCommandUpdate>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TrafficCommandUpdate& from);
  void MergeFrom(const TrafficCommandUpdate& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrafficCommandUpdate* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "osi3.TrafficCommandUpdate";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_osi_5ftrafficcommandupdate_2eproto);
    return ::descriptor_table_osi_5ftrafficcommandupdate_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef TrafficCommandUpdate_DismissedAction DismissedAction;

  // accessors -------------------------------------------------------

  enum : int {
    kDismissedActionFieldNumber = 4,
    kVersionFieldNumber = 1,
    kTimestampFieldNumber = 2,
    kTrafficParticipantIdFieldNumber = 3,
  };
  // repeated .osi3.TrafficCommandUpdate.DismissedAction dismissed_action = 4;
  int dismissed_action_size() const;
  void clear_dismissed_action();
  ::osi3::TrafficCommandUpdate_DismissedAction* mutable_dismissed_action(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osi3::TrafficCommandUpdate_DismissedAction >*
      mutable_dismissed_action();
  const ::osi3::TrafficCommandUpdate_DismissedAction& dismissed_action(int index) const;
  ::osi3::TrafficCommandUpdate_DismissedAction* add_dismissed_action();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osi3::TrafficCommandUpdate_DismissedAction >&
      dismissed_action() const;

  // .osi3.InterfaceVersion version = 1;
  bool has_version() const;
  void clear_version();
  const ::osi3::InterfaceVersion& version() const;
  ::osi3::InterfaceVersion* release_version();
  ::osi3::InterfaceVersion* mutable_version();
  void set_allocated_version(::osi3::InterfaceVersion* version);

  // .osi3.Timestamp timestamp = 2;
  bool has_timestamp() const;
  void clear_timestamp();
  const ::osi3::Timestamp& timestamp() const;
  ::osi3::Timestamp* release_timestamp();
  ::osi3::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::osi3::Timestamp* timestamp);

  // .osi3.Identifier traffic_participant_id = 3;
  bool has_traffic_participant_id() const;
  void clear_traffic_participant_id();
  const ::osi3::Identifier& traffic_participant_id() const;
  ::osi3::Identifier* release_traffic_participant_id();
  ::osi3::Identifier* mutable_traffic_participant_id();
  void set_allocated_traffic_participant_id(::osi3::Identifier* traffic_participant_id);

  // @@protoc_insertion_point(class_scope:osi3.TrafficCommandUpdate)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osi3::TrafficCommandUpdate_DismissedAction > dismissed_action_;
  ::osi3::InterfaceVersion* version_;
  ::osi3::Timestamp* timestamp_;
  ::osi3::Identifier* traffic_participant_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_osi_5ftrafficcommandupdate_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TrafficCommandUpdate_DismissedAction

// .osi3.Identifier dismissed_action_id = 1;
inline bool TrafficCommandUpdate_DismissedAction::has_dismissed_action_id() const {
  return this != internal_default_instance() && dismissed_action_id_ != nullptr;
}
inline const ::osi3::Identifier& TrafficCommandUpdate_DismissedAction::dismissed_action_id() const {
  const ::osi3::Identifier* p = dismissed_action_id_;
  // @@protoc_insertion_point(field_get:osi3.TrafficCommandUpdate.DismissedAction.dismissed_action_id)
  return p != nullptr ? *p : *reinterpret_cast<const ::osi3::Identifier*>(
      &::osi3::_Identifier_default_instance_);
}
inline ::osi3::Identifier* TrafficCommandUpdate_DismissedAction::release_dismissed_action_id() {
  // @@protoc_insertion_point(field_release:osi3.TrafficCommandUpdate.DismissedAction.dismissed_action_id)
  
  ::osi3::Identifier* temp = dismissed_action_id_;
  dismissed_action_id_ = nullptr;
  return temp;
}
inline ::osi3::Identifier* TrafficCommandUpdate_DismissedAction::mutable_dismissed_action_id() {
  
  if (dismissed_action_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::osi3::Identifier>(GetArenaNoVirtual());
    dismissed_action_id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:osi3.TrafficCommandUpdate.DismissedAction.dismissed_action_id)
  return dismissed_action_id_;
}
inline void TrafficCommandUpdate_DismissedAction::set_allocated_dismissed_action_id(::osi3::Identifier* dismissed_action_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(dismissed_action_id_);
  }
  if (dismissed_action_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      dismissed_action_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, dismissed_action_id, submessage_arena);
    }
    
  } else {
    
  }
  dismissed_action_id_ = dismissed_action_id;
  // @@protoc_insertion_point(field_set_allocated:osi3.TrafficCommandUpdate.DismissedAction.dismissed_action_id)
}

// string failure_reason = 2;
inline void TrafficCommandUpdate_DismissedAction::clear_failure_reason() {
  failure_reason_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& TrafficCommandUpdate_DismissedAction::failure_reason() const {
  // @@protoc_insertion_point(field_get:osi3.TrafficCommandUpdate.DismissedAction.failure_reason)
  return failure_reason_.GetNoArena();
}
inline void TrafficCommandUpdate_DismissedAction::set_failure_reason(const std::string& value) {
  
  failure_reason_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:osi3.TrafficCommandUpdate.DismissedAction.failure_reason)
}
inline void TrafficCommandUpdate_DismissedAction::set_failure_reason(std::string&& value) {
  
  failure_reason_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:osi3.TrafficCommandUpdate.DismissedAction.failure_reason)
}
inline void TrafficCommandUpdate_DismissedAction::set_failure_reason(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  failure_reason_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:osi3.TrafficCommandUpdate.DismissedAction.failure_reason)
}
inline void TrafficCommandUpdate_DismissedAction::set_failure_reason(const char* value, size_t size) {
  
  failure_reason_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:osi3.TrafficCommandUpdate.DismissedAction.failure_reason)
}
inline std::string* TrafficCommandUpdate_DismissedAction::mutable_failure_reason() {
  
  // @@protoc_insertion_point(field_mutable:osi3.TrafficCommandUpdate.DismissedAction.failure_reason)
  return failure_reason_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TrafficCommandUpdate_DismissedAction::release_failure_reason() {
  // @@protoc_insertion_point(field_release:osi3.TrafficCommandUpdate.DismissedAction.failure_reason)
  
  return failure_reason_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TrafficCommandUpdate_DismissedAction::set_allocated_failure_reason(std::string* failure_reason) {
  if (failure_reason != nullptr) {
    
  } else {
    
  }
  failure_reason_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), failure_reason);
  // @@protoc_insertion_point(field_set_allocated:osi3.TrafficCommandUpdate.DismissedAction.failure_reason)
}

// -------------------------------------------------------------------

// TrafficCommandUpdate

// .osi3.InterfaceVersion version = 1;
inline bool TrafficCommandUpdate::has_version() const {
  return this != internal_default_instance() && version_ != nullptr;
}
inline const ::osi3::InterfaceVersion& TrafficCommandUpdate::version() const {
  const ::osi3::InterfaceVersion* p = version_;
  // @@protoc_insertion_point(field_get:osi3.TrafficCommandUpdate.version)
  return p != nullptr ? *p : *reinterpret_cast<const ::osi3::InterfaceVersion*>(
      &::osi3::_InterfaceVersion_default_instance_);
}
inline ::osi3::InterfaceVersion* TrafficCommandUpdate::release_version() {
  // @@protoc_insertion_point(field_release:osi3.TrafficCommandUpdate.version)
  
  ::osi3::InterfaceVersion* temp = version_;
  version_ = nullptr;
  return temp;
}
inline ::osi3::InterfaceVersion* TrafficCommandUpdate::mutable_version() {
  
  if (version_ == nullptr) {
    auto* p = CreateMaybeMessage<::osi3::InterfaceVersion>(GetArenaNoVirtual());
    version_ = p;
  }
  // @@protoc_insertion_point(field_mutable:osi3.TrafficCommandUpdate.version)
  return version_;
}
inline void TrafficCommandUpdate::set_allocated_version(::osi3::InterfaceVersion* version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(version_);
  }
  if (version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, version, submessage_arena);
    }
    
  } else {
    
  }
  version_ = version;
  // @@protoc_insertion_point(field_set_allocated:osi3.TrafficCommandUpdate.version)
}

// .osi3.Timestamp timestamp = 2;
inline bool TrafficCommandUpdate::has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline const ::osi3::Timestamp& TrafficCommandUpdate::timestamp() const {
  const ::osi3::Timestamp* p = timestamp_;
  // @@protoc_insertion_point(field_get:osi3.TrafficCommandUpdate.timestamp)
  return p != nullptr ? *p : *reinterpret_cast<const ::osi3::Timestamp*>(
      &::osi3::_Timestamp_default_instance_);
}
inline ::osi3::Timestamp* TrafficCommandUpdate::release_timestamp() {
  // @@protoc_insertion_point(field_release:osi3.TrafficCommandUpdate.timestamp)
  
  ::osi3::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline ::osi3::Timestamp* TrafficCommandUpdate::mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::osi3::Timestamp>(GetArenaNoVirtual());
    timestamp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:osi3.TrafficCommandUpdate.timestamp)
  return timestamp_;
}
inline void TrafficCommandUpdate::set_allocated_timestamp(::osi3::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:osi3.TrafficCommandUpdate.timestamp)
}

// .osi3.Identifier traffic_participant_id = 3;
inline bool TrafficCommandUpdate::has_traffic_participant_id() const {
  return this != internal_default_instance() && traffic_participant_id_ != nullptr;
}
inline const ::osi3::Identifier& TrafficCommandUpdate::traffic_participant_id() const {
  const ::osi3::Identifier* p = traffic_participant_id_;
  // @@protoc_insertion_point(field_get:osi3.TrafficCommandUpdate.traffic_participant_id)
  return p != nullptr ? *p : *reinterpret_cast<const ::osi3::Identifier*>(
      &::osi3::_Identifier_default_instance_);
}
inline ::osi3::Identifier* TrafficCommandUpdate::release_traffic_participant_id() {
  // @@protoc_insertion_point(field_release:osi3.TrafficCommandUpdate.traffic_participant_id)
  
  ::osi3::Identifier* temp = traffic_participant_id_;
  traffic_participant_id_ = nullptr;
  return temp;
}
inline ::osi3::Identifier* TrafficCommandUpdate::mutable_traffic_participant_id() {
  
  if (traffic_participant_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::osi3::Identifier>(GetArenaNoVirtual());
    traffic_participant_id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:osi3.TrafficCommandUpdate.traffic_participant_id)
  return traffic_participant_id_;
}
inline void TrafficCommandUpdate::set_allocated_traffic_participant_id(::osi3::Identifier* traffic_participant_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(traffic_participant_id_);
  }
  if (traffic_participant_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      traffic_participant_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, traffic_participant_id, submessage_arena);
    }
    
  } else {
    
  }
  traffic_participant_id_ = traffic_participant_id;
  // @@protoc_insertion_point(field_set_allocated:osi3.TrafficCommandUpdate.traffic_participant_id)
}

// repeated .osi3.TrafficCommandUpdate.DismissedAction dismissed_action = 4;
inline int TrafficCommandUpdate::dismissed_action_size() const {
  return dismissed_action_.size();
}
inline void TrafficCommandUpdate::clear_dismissed_action() {
  dismissed_action_.Clear();
}
inline ::osi3::TrafficCommandUpdate_DismissedAction* TrafficCommandUpdate::mutable_dismissed_action(int index) {
  // @@protoc_insertion_point(field_mutable:osi3.TrafficCommandUpdate.dismissed_action)
  return dismissed_action_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osi3::TrafficCommandUpdate_DismissedAction >*
TrafficCommandUpdate::mutable_dismissed_action() {
  // @@protoc_insertion_point(field_mutable_list:osi3.TrafficCommandUpdate.dismissed_action)
  return &dismissed_action_;
}
inline const ::osi3::TrafficCommandUpdate_DismissedAction& TrafficCommandUpdate::dismissed_action(int index) const {
  // @@protoc_insertion_point(field_get:osi3.TrafficCommandUpdate.dismissed_action)
  return dismissed_action_.Get(index);
}
inline ::osi3::TrafficCommandUpdate_DismissedAction* TrafficCommandUpdate::add_dismissed_action() {
  // @@protoc_insertion_point(field_add:osi3.TrafficCommandUpdate.dismissed_action)
  return dismissed_action_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osi3::TrafficCommandUpdate_DismissedAction >&
TrafficCommandUpdate::dismissed_action() const {
  // @@protoc_insertion_point(field_list:osi3.TrafficCommandUpdate.dismissed_action)
  return dismissed_action_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace osi3

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_osi_5ftrafficcommandupdate_2eproto
