// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_record.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_pb_5frecord_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_pb_5frecord_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_pb_5frecord_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_pb_5frecord_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pb_5frecord_2eproto;
namespace sim_msg {
class PBRecord;
class PBRecordDefaultTypeInternal;
extern PBRecordDefaultTypeInternal _PBRecord_default_instance_;
}  // namespace sim_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::sim_msg::PBRecord* Arena::CreateMaybeMessage<::sim_msg::PBRecord>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sim_msg {

// ===================================================================

class PBRecord :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sim_msg.PBRecord) */ {
 public:
  PBRecord();
  virtual ~PBRecord();

  PBRecord(const PBRecord& from);
  PBRecord(PBRecord&& from) noexcept
    : PBRecord() {
    *this = ::std::move(from);
  }

  inline PBRecord& operator=(const PBRecord& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBRecord& operator=(PBRecord&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PBRecord& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PBRecord* internal_default_instance() {
    return reinterpret_cast<const PBRecord*>(
               &_PBRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PBRecord& a, PBRecord& b) {
    a.Swap(&b);
  }
  inline void Swap(PBRecord* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PBRecord* New() const final {
    return CreateMaybeMessage<PBRecord>(nullptr);
  }

  PBRecord* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PBRecord>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PBRecord& from);
  void MergeFrom(const PBRecord& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBRecord* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sim_msg.PBRecord";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_pb_5frecord_2eproto);
    return ::descriptor_table_pb_5frecord_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSimTopicFieldNumber = 2,
    kSimPayloadFieldNumber = 3,
    kSimTMsFieldNumber = 1,
  };
  // string sim_topic = 2;
  void clear_sim_topic();
  const std::string& sim_topic() const;
  void set_sim_topic(const std::string& value);
  void set_sim_topic(std::string&& value);
  void set_sim_topic(const char* value);
  void set_sim_topic(const char* value, size_t size);
  std::string* mutable_sim_topic();
  std::string* release_sim_topic();
  void set_allocated_sim_topic(std::string* sim_topic);

  // bytes sim_payload = 3;
  void clear_sim_payload();
  const std::string& sim_payload() const;
  void set_sim_payload(const std::string& value);
  void set_sim_payload(std::string&& value);
  void set_sim_payload(const char* value);
  void set_sim_payload(const void* value, size_t size);
  std::string* mutable_sim_payload();
  std::string* release_sim_payload();
  void set_allocated_sim_payload(std::string* sim_payload);

  // uint64 sim_t_ms = 1;
  void clear_sim_t_ms();
  ::PROTOBUF_NAMESPACE_ID::uint64 sim_t_ms() const;
  void set_sim_t_ms(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:sim_msg.PBRecord)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sim_topic_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sim_payload_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sim_t_ms_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_pb_5frecord_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PBRecord

// uint64 sim_t_ms = 1;
inline void PBRecord::clear_sim_t_ms() {
  sim_t_ms_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PBRecord::sim_t_ms() const {
  // @@protoc_insertion_point(field_get:sim_msg.PBRecord.sim_t_ms)
  return sim_t_ms_;
}
inline void PBRecord::set_sim_t_ms(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  sim_t_ms_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.PBRecord.sim_t_ms)
}

// string sim_topic = 2;
inline void PBRecord::clear_sim_topic() {
  sim_topic_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& PBRecord::sim_topic() const {
  // @@protoc_insertion_point(field_get:sim_msg.PBRecord.sim_topic)
  return sim_topic_.GetNoArena();
}
inline void PBRecord::set_sim_topic(const std::string& value) {
  
  sim_topic_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sim_msg.PBRecord.sim_topic)
}
inline void PBRecord::set_sim_topic(std::string&& value) {
  
  sim_topic_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sim_msg.PBRecord.sim_topic)
}
inline void PBRecord::set_sim_topic(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sim_topic_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sim_msg.PBRecord.sim_topic)
}
inline void PBRecord::set_sim_topic(const char* value, size_t size) {
  
  sim_topic_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sim_msg.PBRecord.sim_topic)
}
inline std::string* PBRecord::mutable_sim_topic() {
  
  // @@protoc_insertion_point(field_mutable:sim_msg.PBRecord.sim_topic)
  return sim_topic_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PBRecord::release_sim_topic() {
  // @@protoc_insertion_point(field_release:sim_msg.PBRecord.sim_topic)
  
  return sim_topic_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PBRecord::set_allocated_sim_topic(std::string* sim_topic) {
  if (sim_topic != nullptr) {
    
  } else {
    
  }
  sim_topic_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sim_topic);
  // @@protoc_insertion_point(field_set_allocated:sim_msg.PBRecord.sim_topic)
}

// bytes sim_payload = 3;
inline void PBRecord::clear_sim_payload() {
  sim_payload_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& PBRecord::sim_payload() const {
  // @@protoc_insertion_point(field_get:sim_msg.PBRecord.sim_payload)
  return sim_payload_.GetNoArena();
}
inline void PBRecord::set_sim_payload(const std::string& value) {
  
  sim_payload_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sim_msg.PBRecord.sim_payload)
}
inline void PBRecord::set_sim_payload(std::string&& value) {
  
  sim_payload_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sim_msg.PBRecord.sim_payload)
}
inline void PBRecord::set_sim_payload(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sim_payload_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sim_msg.PBRecord.sim_payload)
}
inline void PBRecord::set_sim_payload(const void* value, size_t size) {
  
  sim_payload_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sim_msg.PBRecord.sim_payload)
}
inline std::string* PBRecord::mutable_sim_payload() {
  
  // @@protoc_insertion_point(field_mutable:sim_msg.PBRecord.sim_payload)
  return sim_payload_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PBRecord::release_sim_payload() {
  // @@protoc_insertion_point(field_release:sim_msg.PBRecord.sim_payload)
  
  return sim_payload_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PBRecord::set_allocated_sim_payload(std::string* sim_payload) {
  if (sim_payload != nullptr) {
    
  } else {
    
  }
  sim_payload_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sim_payload);
  // @@protoc_insertion_point(field_set_allocated:sim_msg.PBRecord.sim_payload)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace sim_msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_pb_5frecord_2eproto
