// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: perception_obstacles.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_perception_5fobstacles_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_perception_5fobstacles_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "basic.pb.h"
#include "header.pb.h"
#include "trajectory.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_perception_5fobstacles_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_perception_5fobstacles_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_perception_5fobstacles_2eproto;
namespace sim_msg {
class LightStatus;
class LightStatusDefaultTypeInternal;
extern LightStatusDefaultTypeInternal _LightStatus_default_instance_;
class PerceptionObstacle;
class PerceptionObstacleDefaultTypeInternal;
extern PerceptionObstacleDefaultTypeInternal _PerceptionObstacle_default_instance_;
class PerceptionObstacles;
class PerceptionObstaclesDefaultTypeInternal;
extern PerceptionObstaclesDefaultTypeInternal _PerceptionObstacles_default_instance_;
class SubObstacle;
class SubObstacleDefaultTypeInternal;
extern SubObstacleDefaultTypeInternal _SubObstacle_default_instance_;
}  // namespace sim_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::sim_msg::LightStatus* Arena::CreateMaybeMessage<::sim_msg::LightStatus>(Arena*);
template<> ::sim_msg::PerceptionObstacle* Arena::CreateMaybeMessage<::sim_msg::PerceptionObstacle>(Arena*);
template<> ::sim_msg::PerceptionObstacles* Arena::CreateMaybeMessage<::sim_msg::PerceptionObstacles>(Arena*);
template<> ::sim_msg::SubObstacle* Arena::CreateMaybeMessage<::sim_msg::SubObstacle>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sim_msg {

enum PerceptionObstacle_Source : int {
  PerceptionObstacle_Source_HOST_VEHICLE = 0,
  PerceptionObstacle_Source_PLATOON = 1,
  PerceptionObstacle_Source_PerceptionObstacle_Source_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PerceptionObstacle_Source_PerceptionObstacle_Source_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PerceptionObstacle_Source_IsValid(int value);
constexpr PerceptionObstacle_Source PerceptionObstacle_Source_Source_MIN = PerceptionObstacle_Source_HOST_VEHICLE;
constexpr PerceptionObstacle_Source PerceptionObstacle_Source_Source_MAX = PerceptionObstacle_Source_PLATOON;
constexpr int PerceptionObstacle_Source_Source_ARRAYSIZE = PerceptionObstacle_Source_Source_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PerceptionObstacle_Source_descriptor();
template<typename T>
inline const std::string& PerceptionObstacle_Source_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PerceptionObstacle_Source>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PerceptionObstacle_Source_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PerceptionObstacle_Source_descriptor(), enum_t_value);
}
inline bool PerceptionObstacle_Source_Parse(
    const std::string& name, PerceptionObstacle_Source* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PerceptionObstacle_Source>(
    PerceptionObstacle_Source_descriptor(), name, value);
}
enum PerceptionObstacle_Type : int {
  PerceptionObstacle_Type_UNKNOWN = 0,
  PerceptionObstacle_Type_UNKNOWN_MOVABLE = 1,
  PerceptionObstacle_Type_UNKNOWN_UNMOVABLE = 2,
  PerceptionObstacle_Type_PEDESTRIAN = 3,
  PerceptionObstacle_Type_BICYCLE = 4,
  PerceptionObstacle_Type_VEHICLE = 5,
  PerceptionObstacle_Type_BUS = 6,
  PerceptionObstacle_Type_TRUCK = 7,
  PerceptionObstacle_Type_CONES = 8,
  PerceptionObstacle_Type_PLATOON_FRONT_VEHICLE = 9,
  PerceptionObstacle_Type_RTG = 10,
  PerceptionObstacle_Type_PerceptionObstacle_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PerceptionObstacle_Type_PerceptionObstacle_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PerceptionObstacle_Type_IsValid(int value);
constexpr PerceptionObstacle_Type PerceptionObstacle_Type_Type_MIN = PerceptionObstacle_Type_UNKNOWN;
constexpr PerceptionObstacle_Type PerceptionObstacle_Type_Type_MAX = PerceptionObstacle_Type_RTG;
constexpr int PerceptionObstacle_Type_Type_ARRAYSIZE = PerceptionObstacle_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PerceptionObstacle_Type_descriptor();
template<typename T>
inline const std::string& PerceptionObstacle_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PerceptionObstacle_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PerceptionObstacle_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PerceptionObstacle_Type_descriptor(), enum_t_value);
}
inline bool PerceptionObstacle_Type_Parse(
    const std::string& name, PerceptionObstacle_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PerceptionObstacle_Type>(
    PerceptionObstacle_Type_descriptor(), name, value);
}
enum PerceptionObstacle_MoveStatus : int {
  PerceptionObstacle_MoveStatus_UNKNOWN_MOVE = 0,
  PerceptionObstacle_MoveStatus_MOVING = 1,
  PerceptionObstacle_MoveStatus_STOP = 2,
  PerceptionObstacle_MoveStatus_STATIONARY = 3,
  PerceptionObstacle_MoveStatus_PerceptionObstacle_MoveStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PerceptionObstacle_MoveStatus_PerceptionObstacle_MoveStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PerceptionObstacle_MoveStatus_IsValid(int value);
constexpr PerceptionObstacle_MoveStatus PerceptionObstacle_MoveStatus_MoveStatus_MIN = PerceptionObstacle_MoveStatus_UNKNOWN_MOVE;
constexpr PerceptionObstacle_MoveStatus PerceptionObstacle_MoveStatus_MoveStatus_MAX = PerceptionObstacle_MoveStatus_STATIONARY;
constexpr int PerceptionObstacle_MoveStatus_MoveStatus_ARRAYSIZE = PerceptionObstacle_MoveStatus_MoveStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PerceptionObstacle_MoveStatus_descriptor();
template<typename T>
inline const std::string& PerceptionObstacle_MoveStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PerceptionObstacle_MoveStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PerceptionObstacle_MoveStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PerceptionObstacle_MoveStatus_descriptor(), enum_t_value);
}
inline bool PerceptionObstacle_MoveStatus_Parse(
    const std::string& name, PerceptionObstacle_MoveStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PerceptionObstacle_MoveStatus>(
    PerceptionObstacle_MoveStatus_descriptor(), name, value);
}
// ===================================================================

class LightStatus :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sim_msg.LightStatus) */ {
 public:
  LightStatus();
  virtual ~LightStatus();

  LightStatus(const LightStatus& from);
  LightStatus(LightStatus&& from) noexcept
    : LightStatus() {
    *this = ::std::move(from);
  }

  inline LightStatus& operator=(const LightStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline LightStatus& operator=(LightStatus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LightStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LightStatus* internal_default_instance() {
    return reinterpret_cast<const LightStatus*>(
               &_LightStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LightStatus& a, LightStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(LightStatus* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LightStatus* New() const final {
    return CreateMaybeMessage<LightStatus>(nullptr);
  }

  LightStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LightStatus>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LightStatus& from);
  void MergeFrom(const LightStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LightStatus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sim_msg.LightStatus";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_perception_5fobstacles_2eproto);
    return ::descriptor_table_perception_5fobstacles_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBrakeVisibleProbabilityFieldNumber = 1,
    kBrakeSwitchOnProbabilityFieldNumber = 2,
    kLeftTurnVisibleProbabilityFieldNumber = 3,
    kLeftTurnSwitchOnProbabilityFieldNumber = 4,
    kRightTurnVisibleProbabilityFieldNumber = 5,
    kRightTurnSwitchOnProbabilityFieldNumber = 6,
  };
  // int32 brake_visible_probability = 1;
  void clear_brake_visible_probability();
  ::PROTOBUF_NAMESPACE_ID::int32 brake_visible_probability() const;
  void set_brake_visible_probability(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 brake_switch_on_probability = 2;
  void clear_brake_switch_on_probability();
  ::PROTOBUF_NAMESPACE_ID::int32 brake_switch_on_probability() const;
  void set_brake_switch_on_probability(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 left_turn_visible_probability = 3;
  void clear_left_turn_visible_probability();
  ::PROTOBUF_NAMESPACE_ID::int32 left_turn_visible_probability() const;
  void set_left_turn_visible_probability(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 left_turn_switch_on_probability = 4;
  void clear_left_turn_switch_on_probability();
  ::PROTOBUF_NAMESPACE_ID::int32 left_turn_switch_on_probability() const;
  void set_left_turn_switch_on_probability(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 right_turn_visible_probability = 5;
  void clear_right_turn_visible_probability();
  ::PROTOBUF_NAMESPACE_ID::int32 right_turn_visible_probability() const;
  void set_right_turn_visible_probability(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 right_turn_switch_on_probability = 6;
  void clear_right_turn_switch_on_probability();
  ::PROTOBUF_NAMESPACE_ID::int32 right_turn_switch_on_probability() const;
  void set_right_turn_switch_on_probability(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:sim_msg.LightStatus)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 brake_visible_probability_;
  ::PROTOBUF_NAMESPACE_ID::int32 brake_switch_on_probability_;
  ::PROTOBUF_NAMESPACE_ID::int32 left_turn_visible_probability_;
  ::PROTOBUF_NAMESPACE_ID::int32 left_turn_switch_on_probability_;
  ::PROTOBUF_NAMESPACE_ID::int32 right_turn_visible_probability_;
  ::PROTOBUF_NAMESPACE_ID::int32 right_turn_switch_on_probability_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_perception_5fobstacles_2eproto;
};
// -------------------------------------------------------------------

class SubObstacle :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sim_msg.SubObstacle) */ {
 public:
  SubObstacle();
  virtual ~SubObstacle();

  SubObstacle(const SubObstacle& from);
  SubObstacle(SubObstacle&& from) noexcept
    : SubObstacle() {
    *this = ::std::move(from);
  }

  inline SubObstacle& operator=(const SubObstacle& from) {
    CopyFrom(from);
    return *this;
  }
  inline SubObstacle& operator=(SubObstacle&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SubObstacle& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SubObstacle* internal_default_instance() {
    return reinterpret_cast<const SubObstacle*>(
               &_SubObstacle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SubObstacle& a, SubObstacle& b) {
    a.Swap(&b);
  }
  inline void Swap(SubObstacle* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SubObstacle* New() const final {
    return CreateMaybeMessage<SubObstacle>(nullptr);
  }

  SubObstacle* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SubObstacle>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SubObstacle& from);
  void MergeFrom(const SubObstacle& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SubObstacle* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sim_msg.SubObstacle";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_perception_5fobstacles_2eproto);
    return ::descriptor_table_perception_5fobstacles_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kPositionStdFieldNumber = 2,
    kVelocityFieldNumber = 3,
    kVelocityStdFieldNumber = 4,
    kAccelerationFieldNumber = 5,
    kAccelerationStdFieldNumber = 6,
    kPredicTrajectoryFieldNumber = 17,
    kLengthFieldNumber = 7,
    kLengthStdFieldNumber = 8,
    kWidthFieldNumber = 9,
    kWidthStdFieldNumber = 10,
    kHeightFieldNumber = 11,
    kHegihtStdFieldNumber = 12,
    kHeadingAngleFieldNumber = 13,
    kHeadingAngleStdFieldNumber = 14,
    kHeadingRateFieldNumber = 15,
    kHeadingRateStdFieldNumber = 16,
  };
  // .sim_msg.Vec3 position = 1;
  bool has_position() const;
  void clear_position();
  const ::sim_msg::Vec3& position() const;
  ::sim_msg::Vec3* release_position();
  ::sim_msg::Vec3* mutable_position();
  void set_allocated_position(::sim_msg::Vec3* position);

  // .sim_msg.Vec3 position_std = 2;
  bool has_position_std() const;
  void clear_position_std();
  const ::sim_msg::Vec3& position_std() const;
  ::sim_msg::Vec3* release_position_std();
  ::sim_msg::Vec3* mutable_position_std();
  void set_allocated_position_std(::sim_msg::Vec3* position_std);

  // .sim_msg.Vec3 velocity = 3;
  bool has_velocity() const;
  void clear_velocity();
  const ::sim_msg::Vec3& velocity() const;
  ::sim_msg::Vec3* release_velocity();
  ::sim_msg::Vec3* mutable_velocity();
  void set_allocated_velocity(::sim_msg::Vec3* velocity);

  // .sim_msg.Vec3 velocity_std = 4;
  bool has_velocity_std() const;
  void clear_velocity_std();
  const ::sim_msg::Vec3& velocity_std() const;
  ::sim_msg::Vec3* release_velocity_std();
  ::sim_msg::Vec3* mutable_velocity_std();
  void set_allocated_velocity_std(::sim_msg::Vec3* velocity_std);

  // .sim_msg.Vec3 acceleration = 5;
  bool has_acceleration() const;
  void clear_acceleration();
  const ::sim_msg::Vec3& acceleration() const;
  ::sim_msg::Vec3* release_acceleration();
  ::sim_msg::Vec3* mutable_acceleration();
  void set_allocated_acceleration(::sim_msg::Vec3* acceleration);

  // .sim_msg.Vec3 acceleration_std = 6;
  bool has_acceleration_std() const;
  void clear_acceleration_std();
  const ::sim_msg::Vec3& acceleration_std() const;
  ::sim_msg::Vec3* release_acceleration_std();
  ::sim_msg::Vec3* mutable_acceleration_std();
  void set_allocated_acceleration_std(::sim_msg::Vec3* acceleration_std);

  // .sim_msg.Trajectory predic_trajectory = 17;
  bool has_predic_trajectory() const;
  void clear_predic_trajectory();
  const ::sim_msg::Trajectory& predic_trajectory() const;
  ::sim_msg::Trajectory* release_predic_trajectory();
  ::sim_msg::Trajectory* mutable_predic_trajectory();
  void set_allocated_predic_trajectory(::sim_msg::Trajectory* predic_trajectory);

  // float length = 7;
  void clear_length();
  float length() const;
  void set_length(float value);

  // float length_std = 8;
  void clear_length_std();
  float length_std() const;
  void set_length_std(float value);

  // float width = 9;
  void clear_width();
  float width() const;
  void set_width(float value);

  // float width_std = 10;
  void clear_width_std();
  float width_std() const;
  void set_width_std(float value);

  // float height = 11;
  void clear_height();
  float height() const;
  void set_height(float value);

  // float hegiht_std = 12;
  void clear_hegiht_std();
  float hegiht_std() const;
  void set_hegiht_std(float value);

  // float heading_angle = 13;
  void clear_heading_angle();
  float heading_angle() const;
  void set_heading_angle(float value);

  // float heading_angle_std = 14;
  void clear_heading_angle_std();
  float heading_angle_std() const;
  void set_heading_angle_std(float value);

  // float heading_rate = 15;
  void clear_heading_rate();
  float heading_rate() const;
  void set_heading_rate(float value);

  // float heading_rate_std = 16;
  void clear_heading_rate_std();
  float heading_rate_std() const;
  void set_heading_rate_std(float value);

  // @@protoc_insertion_point(class_scope:sim_msg.SubObstacle)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::sim_msg::Vec3* position_;
  ::sim_msg::Vec3* position_std_;
  ::sim_msg::Vec3* velocity_;
  ::sim_msg::Vec3* velocity_std_;
  ::sim_msg::Vec3* acceleration_;
  ::sim_msg::Vec3* acceleration_std_;
  ::sim_msg::Trajectory* predic_trajectory_;
  float length_;
  float length_std_;
  float width_;
  float width_std_;
  float height_;
  float hegiht_std_;
  float heading_angle_;
  float heading_angle_std_;
  float heading_rate_;
  float heading_rate_std_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_perception_5fobstacles_2eproto;
};
// -------------------------------------------------------------------

class PerceptionObstacle :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sim_msg.PerceptionObstacle) */ {
 public:
  PerceptionObstacle();
  virtual ~PerceptionObstacle();

  PerceptionObstacle(const PerceptionObstacle& from);
  PerceptionObstacle(PerceptionObstacle&& from) noexcept
    : PerceptionObstacle() {
    *this = ::std::move(from);
  }

  inline PerceptionObstacle& operator=(const PerceptionObstacle& from) {
    CopyFrom(from);
    return *this;
  }
  inline PerceptionObstacle& operator=(PerceptionObstacle&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PerceptionObstacle& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PerceptionObstacle* internal_default_instance() {
    return reinterpret_cast<const PerceptionObstacle*>(
               &_PerceptionObstacle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PerceptionObstacle& a, PerceptionObstacle& b) {
    a.Swap(&b);
  }
  inline void Swap(PerceptionObstacle* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PerceptionObstacle* New() const final {
    return CreateMaybeMessage<PerceptionObstacle>(nullptr);
  }

  PerceptionObstacle* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PerceptionObstacle>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PerceptionObstacle& from);
  void MergeFrom(const PerceptionObstacle& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PerceptionObstacle* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sim_msg.PerceptionObstacle";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_perception_5fobstacles_2eproto);
    return ::descriptor_table_perception_5fobstacles_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef PerceptionObstacle_Source Source;
  static constexpr Source HOST_VEHICLE =
    PerceptionObstacle_Source_HOST_VEHICLE;
  static constexpr Source PLATOON =
    PerceptionObstacle_Source_PLATOON;
  static inline bool Source_IsValid(int value) {
    return PerceptionObstacle_Source_IsValid(value);
  }
  static constexpr Source Source_MIN =
    PerceptionObstacle_Source_Source_MIN;
  static constexpr Source Source_MAX =
    PerceptionObstacle_Source_Source_MAX;
  static constexpr int Source_ARRAYSIZE =
    PerceptionObstacle_Source_Source_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Source_descriptor() {
    return PerceptionObstacle_Source_descriptor();
  }
  template<typename T>
  static inline const std::string& Source_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Source>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Source_Name.");
    return PerceptionObstacle_Source_Name(enum_t_value);
  }
  static inline bool Source_Parse(const std::string& name,
      Source* value) {
    return PerceptionObstacle_Source_Parse(name, value);
  }

  typedef PerceptionObstacle_Type Type;
  static constexpr Type UNKNOWN =
    PerceptionObstacle_Type_UNKNOWN;
  static constexpr Type UNKNOWN_MOVABLE =
    PerceptionObstacle_Type_UNKNOWN_MOVABLE;
  static constexpr Type UNKNOWN_UNMOVABLE =
    PerceptionObstacle_Type_UNKNOWN_UNMOVABLE;
  static constexpr Type PEDESTRIAN =
    PerceptionObstacle_Type_PEDESTRIAN;
  static constexpr Type BICYCLE =
    PerceptionObstacle_Type_BICYCLE;
  static constexpr Type VEHICLE =
    PerceptionObstacle_Type_VEHICLE;
  static constexpr Type BUS =
    PerceptionObstacle_Type_BUS;
  static constexpr Type TRUCK =
    PerceptionObstacle_Type_TRUCK;
  static constexpr Type CONES =
    PerceptionObstacle_Type_CONES;
  static constexpr Type PLATOON_FRONT_VEHICLE =
    PerceptionObstacle_Type_PLATOON_FRONT_VEHICLE;
  static constexpr Type RTG =
    PerceptionObstacle_Type_RTG;
  static inline bool Type_IsValid(int value) {
    return PerceptionObstacle_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    PerceptionObstacle_Type_Type_MIN;
  static constexpr Type Type_MAX =
    PerceptionObstacle_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    PerceptionObstacle_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return PerceptionObstacle_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return PerceptionObstacle_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(const std::string& name,
      Type* value) {
    return PerceptionObstacle_Type_Parse(name, value);
  }

  typedef PerceptionObstacle_MoveStatus MoveStatus;
  static constexpr MoveStatus UNKNOWN_MOVE =
    PerceptionObstacle_MoveStatus_UNKNOWN_MOVE;
  static constexpr MoveStatus MOVING =
    PerceptionObstacle_MoveStatus_MOVING;
  static constexpr MoveStatus STOP =
    PerceptionObstacle_MoveStatus_STOP;
  static constexpr MoveStatus STATIONARY =
    PerceptionObstacle_MoveStatus_STATIONARY;
  static inline bool MoveStatus_IsValid(int value) {
    return PerceptionObstacle_MoveStatus_IsValid(value);
  }
  static constexpr MoveStatus MoveStatus_MIN =
    PerceptionObstacle_MoveStatus_MoveStatus_MIN;
  static constexpr MoveStatus MoveStatus_MAX =
    PerceptionObstacle_MoveStatus_MoveStatus_MAX;
  static constexpr int MoveStatus_ARRAYSIZE =
    PerceptionObstacle_MoveStatus_MoveStatus_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  MoveStatus_descriptor() {
    return PerceptionObstacle_MoveStatus_descriptor();
  }
  template<typename T>
  static inline const std::string& MoveStatus_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MoveStatus>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MoveStatus_Name.");
    return PerceptionObstacle_MoveStatus_Name(enum_t_value);
  }
  static inline bool MoveStatus_Parse(const std::string& name,
      MoveStatus* value) {
    return PerceptionObstacle_MoveStatus_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSubObstaclesFieldNumber = 2,
    kLightStatusFieldNumber = 4,
    kHistoryTrajectoryFieldNumber = 6,
    kIdFieldNumber = 1,
    kTrackingTimeMsFieldNumber = 3,
    kSourceFieldNumber = 5,
    kTypeFieldNumber = 7,
    kMoveStatusFieldNumber = 8,
  };
  // repeated .sim_msg.SubObstacle sub_obstacles = 2;
  int sub_obstacles_size() const;
  void clear_sub_obstacles();
  ::sim_msg::SubObstacle* mutable_sub_obstacles(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::SubObstacle >*
      mutable_sub_obstacles();
  const ::sim_msg::SubObstacle& sub_obstacles(int index) const;
  ::sim_msg::SubObstacle* add_sub_obstacles();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::SubObstacle >&
      sub_obstacles() const;

  // .sim_msg.LightStatus light_status = 4;
  bool has_light_status() const;
  void clear_light_status();
  const ::sim_msg::LightStatus& light_status() const;
  ::sim_msg::LightStatus* release_light_status();
  ::sim_msg::LightStatus* mutable_light_status();
  void set_allocated_light_status(::sim_msg::LightStatus* light_status);

  // .sim_msg.Trajectory history_trajectory = 6;
  bool has_history_trajectory() const;
  void clear_history_trajectory();
  const ::sim_msg::Trajectory& history_trajectory() const;
  ::sim_msg::Trajectory* release_history_trajectory();
  ::sim_msg::Trajectory* mutable_history_trajectory();
  void set_allocated_history_trajectory(::sim_msg::Trajectory* history_trajectory);

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 tracking_time_ms = 3;
  void clear_tracking_time_ms();
  ::PROTOBUF_NAMESPACE_ID::int32 tracking_time_ms() const;
  void set_tracking_time_ms(::PROTOBUF_NAMESPACE_ID::int32 value);

  // .sim_msg.PerceptionObstacle.Source source = 5;
  void clear_source();
  ::sim_msg::PerceptionObstacle_Source source() const;
  void set_source(::sim_msg::PerceptionObstacle_Source value);

  // .sim_msg.PerceptionObstacle.Type type = 7;
  void clear_type();
  ::sim_msg::PerceptionObstacle_Type type() const;
  void set_type(::sim_msg::PerceptionObstacle_Type value);

  // .sim_msg.PerceptionObstacle.MoveStatus move_status = 8;
  void clear_move_status();
  ::sim_msg::PerceptionObstacle_MoveStatus move_status() const;
  void set_move_status(::sim_msg::PerceptionObstacle_MoveStatus value);

  // @@protoc_insertion_point(class_scope:sim_msg.PerceptionObstacle)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::SubObstacle > sub_obstacles_;
  ::sim_msg::LightStatus* light_status_;
  ::sim_msg::Trajectory* history_trajectory_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  ::PROTOBUF_NAMESPACE_ID::int32 tracking_time_ms_;
  int source_;
  int type_;
  int move_status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_perception_5fobstacles_2eproto;
};
// -------------------------------------------------------------------

class PerceptionObstacles :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sim_msg.PerceptionObstacles) */ {
 public:
  PerceptionObstacles();
  virtual ~PerceptionObstacles();

  PerceptionObstacles(const PerceptionObstacles& from);
  PerceptionObstacles(PerceptionObstacles&& from) noexcept
    : PerceptionObstacles() {
    *this = ::std::move(from);
  }

  inline PerceptionObstacles& operator=(const PerceptionObstacles& from) {
    CopyFrom(from);
    return *this;
  }
  inline PerceptionObstacles& operator=(PerceptionObstacles&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PerceptionObstacles& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PerceptionObstacles* internal_default_instance() {
    return reinterpret_cast<const PerceptionObstacles*>(
               &_PerceptionObstacles_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PerceptionObstacles& a, PerceptionObstacles& b) {
    a.Swap(&b);
  }
  inline void Swap(PerceptionObstacles* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PerceptionObstacles* New() const final {
    return CreateMaybeMessage<PerceptionObstacles>(nullptr);
  }

  PerceptionObstacles* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PerceptionObstacles>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PerceptionObstacles& from);
  void MergeFrom(const PerceptionObstacles& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PerceptionObstacles* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sim_msg.PerceptionObstacles";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_perception_5fobstacles_2eproto);
    return ::descriptor_table_perception_5fobstacles_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPerceptionObstaclesFieldNumber = 2,
    kHeaderFieldNumber = 1,
  };
  // repeated .sim_msg.PerceptionObstacle perception_obstacles = 2;
  int perception_obstacles_size() const;
  void clear_perception_obstacles();
  ::sim_msg::PerceptionObstacle* mutable_perception_obstacles(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::PerceptionObstacle >*
      mutable_perception_obstacles();
  const ::sim_msg::PerceptionObstacle& perception_obstacles(int index) const;
  ::sim_msg::PerceptionObstacle* add_perception_obstacles();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::PerceptionObstacle >&
      perception_obstacles() const;

  // .sim_msg.Header header = 1;
  bool has_header() const;
  void clear_header();
  const ::sim_msg::Header& header() const;
  ::sim_msg::Header* release_header();
  ::sim_msg::Header* mutable_header();
  void set_allocated_header(::sim_msg::Header* header);

  // @@protoc_insertion_point(class_scope:sim_msg.PerceptionObstacles)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::PerceptionObstacle > perception_obstacles_;
  ::sim_msg::Header* header_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_perception_5fobstacles_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LightStatus

// int32 brake_visible_probability = 1;
inline void LightStatus::clear_brake_visible_probability() {
  brake_visible_probability_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LightStatus::brake_visible_probability() const {
  // @@protoc_insertion_point(field_get:sim_msg.LightStatus.brake_visible_probability)
  return brake_visible_probability_;
}
inline void LightStatus::set_brake_visible_probability(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  brake_visible_probability_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.LightStatus.brake_visible_probability)
}

// int32 brake_switch_on_probability = 2;
inline void LightStatus::clear_brake_switch_on_probability() {
  brake_switch_on_probability_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LightStatus::brake_switch_on_probability() const {
  // @@protoc_insertion_point(field_get:sim_msg.LightStatus.brake_switch_on_probability)
  return brake_switch_on_probability_;
}
inline void LightStatus::set_brake_switch_on_probability(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  brake_switch_on_probability_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.LightStatus.brake_switch_on_probability)
}

// int32 left_turn_visible_probability = 3;
inline void LightStatus::clear_left_turn_visible_probability() {
  left_turn_visible_probability_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LightStatus::left_turn_visible_probability() const {
  // @@protoc_insertion_point(field_get:sim_msg.LightStatus.left_turn_visible_probability)
  return left_turn_visible_probability_;
}
inline void LightStatus::set_left_turn_visible_probability(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  left_turn_visible_probability_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.LightStatus.left_turn_visible_probability)
}

// int32 left_turn_switch_on_probability = 4;
inline void LightStatus::clear_left_turn_switch_on_probability() {
  left_turn_switch_on_probability_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LightStatus::left_turn_switch_on_probability() const {
  // @@protoc_insertion_point(field_get:sim_msg.LightStatus.left_turn_switch_on_probability)
  return left_turn_switch_on_probability_;
}
inline void LightStatus::set_left_turn_switch_on_probability(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  left_turn_switch_on_probability_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.LightStatus.left_turn_switch_on_probability)
}

// int32 right_turn_visible_probability = 5;
inline void LightStatus::clear_right_turn_visible_probability() {
  right_turn_visible_probability_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LightStatus::right_turn_visible_probability() const {
  // @@protoc_insertion_point(field_get:sim_msg.LightStatus.right_turn_visible_probability)
  return right_turn_visible_probability_;
}
inline void LightStatus::set_right_turn_visible_probability(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  right_turn_visible_probability_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.LightStatus.right_turn_visible_probability)
}

// int32 right_turn_switch_on_probability = 6;
inline void LightStatus::clear_right_turn_switch_on_probability() {
  right_turn_switch_on_probability_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LightStatus::right_turn_switch_on_probability() const {
  // @@protoc_insertion_point(field_get:sim_msg.LightStatus.right_turn_switch_on_probability)
  return right_turn_switch_on_probability_;
}
inline void LightStatus::set_right_turn_switch_on_probability(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  right_turn_switch_on_probability_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.LightStatus.right_turn_switch_on_probability)
}

// -------------------------------------------------------------------

// SubObstacle

// .sim_msg.Vec3 position = 1;
inline bool SubObstacle::has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline const ::sim_msg::Vec3& SubObstacle::position() const {
  const ::sim_msg::Vec3* p = position_;
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.position)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Vec3*>(
      &::sim_msg::_Vec3_default_instance_);
}
inline ::sim_msg::Vec3* SubObstacle::release_position() {
  // @@protoc_insertion_point(field_release:sim_msg.SubObstacle.position)
  
  ::sim_msg::Vec3* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::sim_msg::Vec3* SubObstacle::mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Vec3>(GetArenaNoVirtual());
    position_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.SubObstacle.position)
  return position_;
}
inline void SubObstacle::set_allocated_position(::sim_msg::Vec3* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.SubObstacle.position)
}

// .sim_msg.Vec3 position_std = 2;
inline bool SubObstacle::has_position_std() const {
  return this != internal_default_instance() && position_std_ != nullptr;
}
inline const ::sim_msg::Vec3& SubObstacle::position_std() const {
  const ::sim_msg::Vec3* p = position_std_;
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.position_std)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Vec3*>(
      &::sim_msg::_Vec3_default_instance_);
}
inline ::sim_msg::Vec3* SubObstacle::release_position_std() {
  // @@protoc_insertion_point(field_release:sim_msg.SubObstacle.position_std)
  
  ::sim_msg::Vec3* temp = position_std_;
  position_std_ = nullptr;
  return temp;
}
inline ::sim_msg::Vec3* SubObstacle::mutable_position_std() {
  
  if (position_std_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Vec3>(GetArenaNoVirtual());
    position_std_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.SubObstacle.position_std)
  return position_std_;
}
inline void SubObstacle::set_allocated_position_std(::sim_msg::Vec3* position_std) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_std_);
  }
  if (position_std) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      position_std = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position_std, submessage_arena);
    }
    
  } else {
    
  }
  position_std_ = position_std;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.SubObstacle.position_std)
}

// .sim_msg.Vec3 velocity = 3;
inline bool SubObstacle::has_velocity() const {
  return this != internal_default_instance() && velocity_ != nullptr;
}
inline const ::sim_msg::Vec3& SubObstacle::velocity() const {
  const ::sim_msg::Vec3* p = velocity_;
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.velocity)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Vec3*>(
      &::sim_msg::_Vec3_default_instance_);
}
inline ::sim_msg::Vec3* SubObstacle::release_velocity() {
  // @@protoc_insertion_point(field_release:sim_msg.SubObstacle.velocity)
  
  ::sim_msg::Vec3* temp = velocity_;
  velocity_ = nullptr;
  return temp;
}
inline ::sim_msg::Vec3* SubObstacle::mutable_velocity() {
  
  if (velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Vec3>(GetArenaNoVirtual());
    velocity_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.SubObstacle.velocity)
  return velocity_;
}
inline void SubObstacle::set_allocated_velocity(::sim_msg::Vec3* velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(velocity_);
  }
  if (velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, velocity, submessage_arena);
    }
    
  } else {
    
  }
  velocity_ = velocity;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.SubObstacle.velocity)
}

// .sim_msg.Vec3 velocity_std = 4;
inline bool SubObstacle::has_velocity_std() const {
  return this != internal_default_instance() && velocity_std_ != nullptr;
}
inline const ::sim_msg::Vec3& SubObstacle::velocity_std() const {
  const ::sim_msg::Vec3* p = velocity_std_;
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.velocity_std)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Vec3*>(
      &::sim_msg::_Vec3_default_instance_);
}
inline ::sim_msg::Vec3* SubObstacle::release_velocity_std() {
  // @@protoc_insertion_point(field_release:sim_msg.SubObstacle.velocity_std)
  
  ::sim_msg::Vec3* temp = velocity_std_;
  velocity_std_ = nullptr;
  return temp;
}
inline ::sim_msg::Vec3* SubObstacle::mutable_velocity_std() {
  
  if (velocity_std_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Vec3>(GetArenaNoVirtual());
    velocity_std_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.SubObstacle.velocity_std)
  return velocity_std_;
}
inline void SubObstacle::set_allocated_velocity_std(::sim_msg::Vec3* velocity_std) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(velocity_std_);
  }
  if (velocity_std) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      velocity_std = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, velocity_std, submessage_arena);
    }
    
  } else {
    
  }
  velocity_std_ = velocity_std;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.SubObstacle.velocity_std)
}

// .sim_msg.Vec3 acceleration = 5;
inline bool SubObstacle::has_acceleration() const {
  return this != internal_default_instance() && acceleration_ != nullptr;
}
inline const ::sim_msg::Vec3& SubObstacle::acceleration() const {
  const ::sim_msg::Vec3* p = acceleration_;
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.acceleration)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Vec3*>(
      &::sim_msg::_Vec3_default_instance_);
}
inline ::sim_msg::Vec3* SubObstacle::release_acceleration() {
  // @@protoc_insertion_point(field_release:sim_msg.SubObstacle.acceleration)
  
  ::sim_msg::Vec3* temp = acceleration_;
  acceleration_ = nullptr;
  return temp;
}
inline ::sim_msg::Vec3* SubObstacle::mutable_acceleration() {
  
  if (acceleration_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Vec3>(GetArenaNoVirtual());
    acceleration_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.SubObstacle.acceleration)
  return acceleration_;
}
inline void SubObstacle::set_allocated_acceleration(::sim_msg::Vec3* acceleration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(acceleration_);
  }
  if (acceleration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      acceleration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, acceleration, submessage_arena);
    }
    
  } else {
    
  }
  acceleration_ = acceleration;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.SubObstacle.acceleration)
}

// .sim_msg.Vec3 acceleration_std = 6;
inline bool SubObstacle::has_acceleration_std() const {
  return this != internal_default_instance() && acceleration_std_ != nullptr;
}
inline const ::sim_msg::Vec3& SubObstacle::acceleration_std() const {
  const ::sim_msg::Vec3* p = acceleration_std_;
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.acceleration_std)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Vec3*>(
      &::sim_msg::_Vec3_default_instance_);
}
inline ::sim_msg::Vec3* SubObstacle::release_acceleration_std() {
  // @@protoc_insertion_point(field_release:sim_msg.SubObstacle.acceleration_std)
  
  ::sim_msg::Vec3* temp = acceleration_std_;
  acceleration_std_ = nullptr;
  return temp;
}
inline ::sim_msg::Vec3* SubObstacle::mutable_acceleration_std() {
  
  if (acceleration_std_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Vec3>(GetArenaNoVirtual());
    acceleration_std_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.SubObstacle.acceleration_std)
  return acceleration_std_;
}
inline void SubObstacle::set_allocated_acceleration_std(::sim_msg::Vec3* acceleration_std) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(acceleration_std_);
  }
  if (acceleration_std) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      acceleration_std = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, acceleration_std, submessage_arena);
    }
    
  } else {
    
  }
  acceleration_std_ = acceleration_std;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.SubObstacle.acceleration_std)
}

// float length = 7;
inline void SubObstacle::clear_length() {
  length_ = 0;
}
inline float SubObstacle::length() const {
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.length)
  return length_;
}
inline void SubObstacle::set_length(float value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.SubObstacle.length)
}

// float length_std = 8;
inline void SubObstacle::clear_length_std() {
  length_std_ = 0;
}
inline float SubObstacle::length_std() const {
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.length_std)
  return length_std_;
}
inline void SubObstacle::set_length_std(float value) {
  
  length_std_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.SubObstacle.length_std)
}

// float width = 9;
inline void SubObstacle::clear_width() {
  width_ = 0;
}
inline float SubObstacle::width() const {
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.width)
  return width_;
}
inline void SubObstacle::set_width(float value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.SubObstacle.width)
}

// float width_std = 10;
inline void SubObstacle::clear_width_std() {
  width_std_ = 0;
}
inline float SubObstacle::width_std() const {
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.width_std)
  return width_std_;
}
inline void SubObstacle::set_width_std(float value) {
  
  width_std_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.SubObstacle.width_std)
}

// float height = 11;
inline void SubObstacle::clear_height() {
  height_ = 0;
}
inline float SubObstacle::height() const {
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.height)
  return height_;
}
inline void SubObstacle::set_height(float value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.SubObstacle.height)
}

// float hegiht_std = 12;
inline void SubObstacle::clear_hegiht_std() {
  hegiht_std_ = 0;
}
inline float SubObstacle::hegiht_std() const {
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.hegiht_std)
  return hegiht_std_;
}
inline void SubObstacle::set_hegiht_std(float value) {
  
  hegiht_std_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.SubObstacle.hegiht_std)
}

// float heading_angle = 13;
inline void SubObstacle::clear_heading_angle() {
  heading_angle_ = 0;
}
inline float SubObstacle::heading_angle() const {
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.heading_angle)
  return heading_angle_;
}
inline void SubObstacle::set_heading_angle(float value) {
  
  heading_angle_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.SubObstacle.heading_angle)
}

// float heading_angle_std = 14;
inline void SubObstacle::clear_heading_angle_std() {
  heading_angle_std_ = 0;
}
inline float SubObstacle::heading_angle_std() const {
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.heading_angle_std)
  return heading_angle_std_;
}
inline void SubObstacle::set_heading_angle_std(float value) {
  
  heading_angle_std_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.SubObstacle.heading_angle_std)
}

// float heading_rate = 15;
inline void SubObstacle::clear_heading_rate() {
  heading_rate_ = 0;
}
inline float SubObstacle::heading_rate() const {
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.heading_rate)
  return heading_rate_;
}
inline void SubObstacle::set_heading_rate(float value) {
  
  heading_rate_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.SubObstacle.heading_rate)
}

// float heading_rate_std = 16;
inline void SubObstacle::clear_heading_rate_std() {
  heading_rate_std_ = 0;
}
inline float SubObstacle::heading_rate_std() const {
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.heading_rate_std)
  return heading_rate_std_;
}
inline void SubObstacle::set_heading_rate_std(float value) {
  
  heading_rate_std_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.SubObstacle.heading_rate_std)
}

// .sim_msg.Trajectory predic_trajectory = 17;
inline bool SubObstacle::has_predic_trajectory() const {
  return this != internal_default_instance() && predic_trajectory_ != nullptr;
}
inline const ::sim_msg::Trajectory& SubObstacle::predic_trajectory() const {
  const ::sim_msg::Trajectory* p = predic_trajectory_;
  // @@protoc_insertion_point(field_get:sim_msg.SubObstacle.predic_trajectory)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Trajectory*>(
      &::sim_msg::_Trajectory_default_instance_);
}
inline ::sim_msg::Trajectory* SubObstacle::release_predic_trajectory() {
  // @@protoc_insertion_point(field_release:sim_msg.SubObstacle.predic_trajectory)
  
  ::sim_msg::Trajectory* temp = predic_trajectory_;
  predic_trajectory_ = nullptr;
  return temp;
}
inline ::sim_msg::Trajectory* SubObstacle::mutable_predic_trajectory() {
  
  if (predic_trajectory_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Trajectory>(GetArenaNoVirtual());
    predic_trajectory_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.SubObstacle.predic_trajectory)
  return predic_trajectory_;
}
inline void SubObstacle::set_allocated_predic_trajectory(::sim_msg::Trajectory* predic_trajectory) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(predic_trajectory_);
  }
  if (predic_trajectory) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      predic_trajectory = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, predic_trajectory, submessage_arena);
    }
    
  } else {
    
  }
  predic_trajectory_ = predic_trajectory;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.SubObstacle.predic_trajectory)
}

// -------------------------------------------------------------------

// PerceptionObstacle

// int32 id = 1;
inline void PerceptionObstacle::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PerceptionObstacle::id() const {
  // @@protoc_insertion_point(field_get:sim_msg.PerceptionObstacle.id)
  return id_;
}
inline void PerceptionObstacle::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.PerceptionObstacle.id)
}

// repeated .sim_msg.SubObstacle sub_obstacles = 2;
inline int PerceptionObstacle::sub_obstacles_size() const {
  return sub_obstacles_.size();
}
inline void PerceptionObstacle::clear_sub_obstacles() {
  sub_obstacles_.Clear();
}
inline ::sim_msg::SubObstacle* PerceptionObstacle::mutable_sub_obstacles(int index) {
  // @@protoc_insertion_point(field_mutable:sim_msg.PerceptionObstacle.sub_obstacles)
  return sub_obstacles_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::SubObstacle >*
PerceptionObstacle::mutable_sub_obstacles() {
  // @@protoc_insertion_point(field_mutable_list:sim_msg.PerceptionObstacle.sub_obstacles)
  return &sub_obstacles_;
}
inline const ::sim_msg::SubObstacle& PerceptionObstacle::sub_obstacles(int index) const {
  // @@protoc_insertion_point(field_get:sim_msg.PerceptionObstacle.sub_obstacles)
  return sub_obstacles_.Get(index);
}
inline ::sim_msg::SubObstacle* PerceptionObstacle::add_sub_obstacles() {
  // @@protoc_insertion_point(field_add:sim_msg.PerceptionObstacle.sub_obstacles)
  return sub_obstacles_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::SubObstacle >&
PerceptionObstacle::sub_obstacles() const {
  // @@protoc_insertion_point(field_list:sim_msg.PerceptionObstacle.sub_obstacles)
  return sub_obstacles_;
}

// int32 tracking_time_ms = 3;
inline void PerceptionObstacle::clear_tracking_time_ms() {
  tracking_time_ms_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PerceptionObstacle::tracking_time_ms() const {
  // @@protoc_insertion_point(field_get:sim_msg.PerceptionObstacle.tracking_time_ms)
  return tracking_time_ms_;
}
inline void PerceptionObstacle::set_tracking_time_ms(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  tracking_time_ms_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.PerceptionObstacle.tracking_time_ms)
}

// .sim_msg.LightStatus light_status = 4;
inline bool PerceptionObstacle::has_light_status() const {
  return this != internal_default_instance() && light_status_ != nullptr;
}
inline void PerceptionObstacle::clear_light_status() {
  if (GetArenaNoVirtual() == nullptr && light_status_ != nullptr) {
    delete light_status_;
  }
  light_status_ = nullptr;
}
inline const ::sim_msg::LightStatus& PerceptionObstacle::light_status() const {
  const ::sim_msg::LightStatus* p = light_status_;
  // @@protoc_insertion_point(field_get:sim_msg.PerceptionObstacle.light_status)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::LightStatus*>(
      &::sim_msg::_LightStatus_default_instance_);
}
inline ::sim_msg::LightStatus* PerceptionObstacle::release_light_status() {
  // @@protoc_insertion_point(field_release:sim_msg.PerceptionObstacle.light_status)
  
  ::sim_msg::LightStatus* temp = light_status_;
  light_status_ = nullptr;
  return temp;
}
inline ::sim_msg::LightStatus* PerceptionObstacle::mutable_light_status() {
  
  if (light_status_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::LightStatus>(GetArenaNoVirtual());
    light_status_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.PerceptionObstacle.light_status)
  return light_status_;
}
inline void PerceptionObstacle::set_allocated_light_status(::sim_msg::LightStatus* light_status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete light_status_;
  }
  if (light_status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      light_status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, light_status, submessage_arena);
    }
    
  } else {
    
  }
  light_status_ = light_status;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.PerceptionObstacle.light_status)
}

// .sim_msg.PerceptionObstacle.Source source = 5;
inline void PerceptionObstacle::clear_source() {
  source_ = 0;
}
inline ::sim_msg::PerceptionObstacle_Source PerceptionObstacle::source() const {
  // @@protoc_insertion_point(field_get:sim_msg.PerceptionObstacle.source)
  return static_cast< ::sim_msg::PerceptionObstacle_Source >(source_);
}
inline void PerceptionObstacle::set_source(::sim_msg::PerceptionObstacle_Source value) {
  
  source_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.PerceptionObstacle.source)
}

// .sim_msg.Trajectory history_trajectory = 6;
inline bool PerceptionObstacle::has_history_trajectory() const {
  return this != internal_default_instance() && history_trajectory_ != nullptr;
}
inline const ::sim_msg::Trajectory& PerceptionObstacle::history_trajectory() const {
  const ::sim_msg::Trajectory* p = history_trajectory_;
  // @@protoc_insertion_point(field_get:sim_msg.PerceptionObstacle.history_trajectory)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Trajectory*>(
      &::sim_msg::_Trajectory_default_instance_);
}
inline ::sim_msg::Trajectory* PerceptionObstacle::release_history_trajectory() {
  // @@protoc_insertion_point(field_release:sim_msg.PerceptionObstacle.history_trajectory)
  
  ::sim_msg::Trajectory* temp = history_trajectory_;
  history_trajectory_ = nullptr;
  return temp;
}
inline ::sim_msg::Trajectory* PerceptionObstacle::mutable_history_trajectory() {
  
  if (history_trajectory_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Trajectory>(GetArenaNoVirtual());
    history_trajectory_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.PerceptionObstacle.history_trajectory)
  return history_trajectory_;
}
inline void PerceptionObstacle::set_allocated_history_trajectory(::sim_msg::Trajectory* history_trajectory) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(history_trajectory_);
  }
  if (history_trajectory) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      history_trajectory = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, history_trajectory, submessage_arena);
    }
    
  } else {
    
  }
  history_trajectory_ = history_trajectory;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.PerceptionObstacle.history_trajectory)
}

// .sim_msg.PerceptionObstacle.Type type = 7;
inline void PerceptionObstacle::clear_type() {
  type_ = 0;
}
inline ::sim_msg::PerceptionObstacle_Type PerceptionObstacle::type() const {
  // @@protoc_insertion_point(field_get:sim_msg.PerceptionObstacle.type)
  return static_cast< ::sim_msg::PerceptionObstacle_Type >(type_);
}
inline void PerceptionObstacle::set_type(::sim_msg::PerceptionObstacle_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.PerceptionObstacle.type)
}

// .sim_msg.PerceptionObstacle.MoveStatus move_status = 8;
inline void PerceptionObstacle::clear_move_status() {
  move_status_ = 0;
}
inline ::sim_msg::PerceptionObstacle_MoveStatus PerceptionObstacle::move_status() const {
  // @@protoc_insertion_point(field_get:sim_msg.PerceptionObstacle.move_status)
  return static_cast< ::sim_msg::PerceptionObstacle_MoveStatus >(move_status_);
}
inline void PerceptionObstacle::set_move_status(::sim_msg::PerceptionObstacle_MoveStatus value) {
  
  move_status_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.PerceptionObstacle.move_status)
}

// -------------------------------------------------------------------

// PerceptionObstacles

// .sim_msg.Header header = 1;
inline bool PerceptionObstacles::has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline const ::sim_msg::Header& PerceptionObstacles::header() const {
  const ::sim_msg::Header* p = header_;
  // @@protoc_insertion_point(field_get:sim_msg.PerceptionObstacles.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Header*>(
      &::sim_msg::_Header_default_instance_);
}
inline ::sim_msg::Header* PerceptionObstacles::release_header() {
  // @@protoc_insertion_point(field_release:sim_msg.PerceptionObstacles.header)
  
  ::sim_msg::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::sim_msg::Header* PerceptionObstacles::mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.PerceptionObstacles.header)
  return header_;
}
inline void PerceptionObstacles::set_allocated_header(::sim_msg::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.PerceptionObstacles.header)
}

// repeated .sim_msg.PerceptionObstacle perception_obstacles = 2;
inline int PerceptionObstacles::perception_obstacles_size() const {
  return perception_obstacles_.size();
}
inline void PerceptionObstacles::clear_perception_obstacles() {
  perception_obstacles_.Clear();
}
inline ::sim_msg::PerceptionObstacle* PerceptionObstacles::mutable_perception_obstacles(int index) {
  // @@protoc_insertion_point(field_mutable:sim_msg.PerceptionObstacles.perception_obstacles)
  return perception_obstacles_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::PerceptionObstacle >*
PerceptionObstacles::mutable_perception_obstacles() {
  // @@protoc_insertion_point(field_mutable_list:sim_msg.PerceptionObstacles.perception_obstacles)
  return &perception_obstacles_;
}
inline const ::sim_msg::PerceptionObstacle& PerceptionObstacles::perception_obstacles(int index) const {
  // @@protoc_insertion_point(field_get:sim_msg.PerceptionObstacles.perception_obstacles)
  return perception_obstacles_.Get(index);
}
inline ::sim_msg::PerceptionObstacle* PerceptionObstacles::add_perception_obstacles() {
  // @@protoc_insertion_point(field_add:sim_msg.PerceptionObstacles.perception_obstacles)
  return perception_obstacles_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sim_msg::PerceptionObstacle >&
PerceptionObstacles::perception_obstacles() const {
  // @@protoc_insertion_point(field_list:sim_msg.PerceptionObstacles.perception_obstacles)
  return perception_obstacles_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sim_msg

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::sim_msg::PerceptionObstacle_Source> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sim_msg::PerceptionObstacle_Source>() {
  return ::sim_msg::PerceptionObstacle_Source_descriptor();
}
template <> struct is_proto_enum< ::sim_msg::PerceptionObstacle_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sim_msg::PerceptionObstacle_Type>() {
  return ::sim_msg::PerceptionObstacle_Type_descriptor();
}
template <> struct is_proto_enum< ::sim_msg::PerceptionObstacle_MoveStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sim_msg::PerceptionObstacle_MoveStatus>() {
  return ::sim_msg::PerceptionObstacle_MoveStatus_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_perception_5fobstacles_2eproto
