// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: regionBasic.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_regionBasic_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_regionBasic_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "basic.pb.h"
#include "location.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_regionBasic_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_regionBasic_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_regionBasic_2eproto;
namespace sim_msg {
class EgoCarInfo;
class EgoCarInfoDefaultTypeInternal;
extern EgoCarInfoDefaultTypeInternal _EgoCarInfo_default_instance_;
class ErrorEgoCarInfo;
class ErrorEgoCarInfoDefaultTypeInternal;
extern ErrorEgoCarInfoDefaultTypeInternal _ErrorEgoCarInfo_default_instance_;
}  // namespace sim_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::sim_msg::EgoCarInfo* Arena::CreateMaybeMessage<::sim_msg::EgoCarInfo>(Arena*);
template<> ::sim_msg::ErrorEgoCarInfo* Arena::CreateMaybeMessage<::sim_msg::ErrorEgoCarInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sim_msg {

enum MapPosition : int {
  MAP_POSITION_TOP = 0,
  MAP_POSITION_TOP_LEFT = 1,
  MAP_POSITION_LEFT = 2,
  MAP_POSITION_BOTTOM_LEFT = 3,
  MAP_POSITION_BOTTOM = 4,
  MAP_POSITION_BOTTOM_RIGHT = 5,
  MAP_POSITION_RIGHT = 6,
  MAP_POSITION_TOP_RIGHT = 7,
  MAP_POSITION_NONE = 8,
  MapPosition_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  MapPosition_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool MapPosition_IsValid(int value);
constexpr MapPosition MapPosition_MIN = MAP_POSITION_TOP;
constexpr MapPosition MapPosition_MAX = MAP_POSITION_NONE;
constexpr int MapPosition_ARRAYSIZE = MapPosition_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MapPosition_descriptor();
template<typename T>
inline const std::string& MapPosition_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MapPosition>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MapPosition_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MapPosition_descriptor(), enum_t_value);
}
inline bool MapPosition_Parse(
    const std::string& name, MapPosition* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MapPosition>(
    MapPosition_descriptor(), name, value);
}
// ===================================================================

class EgoCarInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sim_msg.EgoCarInfo) */ {
 public:
  EgoCarInfo();
  virtual ~EgoCarInfo();

  EgoCarInfo(const EgoCarInfo& from);
  EgoCarInfo(EgoCarInfo&& from) noexcept
    : EgoCarInfo() {
    *this = ::std::move(from);
  }

  inline EgoCarInfo& operator=(const EgoCarInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline EgoCarInfo& operator=(EgoCarInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EgoCarInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EgoCarInfo* internal_default_instance() {
    return reinterpret_cast<const EgoCarInfo*>(
               &_EgoCarInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EgoCarInfo& a, EgoCarInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(EgoCarInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EgoCarInfo* New() const final {
    return CreateMaybeMessage<EgoCarInfo>(nullptr);
  }

  EgoCarInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EgoCarInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EgoCarInfo& from);
  void MergeFrom(const EgoCarInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EgoCarInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sim_msg.EgoCarInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_regionBasic_2eproto);
    return ::descriptor_table_regionBasic_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 2,
    kStartPosFieldNumber = 4,
    kLocationFieldNumber = 5,
    kIdFieldNumber = 1,
    kPortFieldNumber = 3,
  };
  // string ip = 2;
  void clear_ip();
  const std::string& ip() const;
  void set_ip(const std::string& value);
  void set_ip(std::string&& value);
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  std::string* mutable_ip();
  std::string* release_ip();
  void set_allocated_ip(std::string* ip);

  // .sim_msg.Vec3 start_pos = 4;
  bool has_start_pos() const;
  void clear_start_pos();
  const ::sim_msg::Vec3& start_pos() const;
  ::sim_msg::Vec3* release_start_pos();
  ::sim_msg::Vec3* mutable_start_pos();
  void set_allocated_start_pos(::sim_msg::Vec3* start_pos);

  // .sim_msg.Location location = 5;
  bool has_location() const;
  void clear_location();
  const ::sim_msg::Location& location() const;
  ::sim_msg::Location* release_location();
  ::sim_msg::Location* mutable_location();
  void set_allocated_location(::sim_msg::Location* location);

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 port = 3;
  void clear_port();
  ::PROTOBUF_NAMESPACE_ID::int32 port() const;
  void set_port(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:sim_msg.EgoCarInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
  ::sim_msg::Vec3* start_pos_;
  ::sim_msg::Location* location_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  ::PROTOBUF_NAMESPACE_ID::int32 port_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_regionBasic_2eproto;
};
// -------------------------------------------------------------------

class ErrorEgoCarInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sim_msg.ErrorEgoCarInfo) */ {
 public:
  ErrorEgoCarInfo();
  virtual ~ErrorEgoCarInfo();

  ErrorEgoCarInfo(const ErrorEgoCarInfo& from);
  ErrorEgoCarInfo(ErrorEgoCarInfo&& from) noexcept
    : ErrorEgoCarInfo() {
    *this = ::std::move(from);
  }

  inline ErrorEgoCarInfo& operator=(const ErrorEgoCarInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ErrorEgoCarInfo& operator=(ErrorEgoCarInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ErrorEgoCarInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ErrorEgoCarInfo* internal_default_instance() {
    return reinterpret_cast<const ErrorEgoCarInfo*>(
               &_ErrorEgoCarInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ErrorEgoCarInfo& a, ErrorEgoCarInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ErrorEgoCarInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ErrorEgoCarInfo* New() const final {
    return CreateMaybeMessage<ErrorEgoCarInfo>(nullptr);
  }

  ErrorEgoCarInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ErrorEgoCarInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ErrorEgoCarInfo& from);
  void MergeFrom(const ErrorEgoCarInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ErrorEgoCarInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sim_msg.ErrorEgoCarInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_regionBasic_2eproto);
    return ::descriptor_table_regionBasic_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLocationFieldNumber = 2,
    kCarIdFieldNumber = 1,
  };
  // .sim_msg.Vec3 location = 2;
  bool has_location() const;
  void clear_location();
  const ::sim_msg::Vec3& location() const;
  ::sim_msg::Vec3* release_location();
  ::sim_msg::Vec3* mutable_location();
  void set_allocated_location(::sim_msg::Vec3* location);

  // int32 car_id = 1;
  void clear_car_id();
  ::PROTOBUF_NAMESPACE_ID::int32 car_id() const;
  void set_car_id(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:sim_msg.ErrorEgoCarInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::sim_msg::Vec3* location_;
  ::PROTOBUF_NAMESPACE_ID::int32 car_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_regionBasic_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EgoCarInfo

// int32 id = 1;
inline void EgoCarInfo::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EgoCarInfo::id() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoCarInfo.id)
  return id_;
}
inline void EgoCarInfo::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoCarInfo.id)
}

// string ip = 2;
inline void EgoCarInfo::clear_ip() {
  ip_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& EgoCarInfo::ip() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoCarInfo.ip)
  return ip_.GetNoArena();
}
inline void EgoCarInfo::set_ip(const std::string& value) {
  
  ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sim_msg.EgoCarInfo.ip)
}
inline void EgoCarInfo::set_ip(std::string&& value) {
  
  ip_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sim_msg.EgoCarInfo.ip)
}
inline void EgoCarInfo::set_ip(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sim_msg.EgoCarInfo.ip)
}
inline void EgoCarInfo::set_ip(const char* value, size_t size) {
  
  ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sim_msg.EgoCarInfo.ip)
}
inline std::string* EgoCarInfo::mutable_ip() {
  
  // @@protoc_insertion_point(field_mutable:sim_msg.EgoCarInfo.ip)
  return ip_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EgoCarInfo::release_ip() {
  // @@protoc_insertion_point(field_release:sim_msg.EgoCarInfo.ip)
  
  return ip_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EgoCarInfo::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    
  } else {
    
  }
  ip_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:sim_msg.EgoCarInfo.ip)
}

// int32 port = 3;
inline void EgoCarInfo::clear_port() {
  port_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EgoCarInfo::port() const {
  // @@protoc_insertion_point(field_get:sim_msg.EgoCarInfo.port)
  return port_;
}
inline void EgoCarInfo::set_port(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.EgoCarInfo.port)
}

// .sim_msg.Vec3 start_pos = 4;
inline bool EgoCarInfo::has_start_pos() const {
  return this != internal_default_instance() && start_pos_ != nullptr;
}
inline const ::sim_msg::Vec3& EgoCarInfo::start_pos() const {
  const ::sim_msg::Vec3* p = start_pos_;
  // @@protoc_insertion_point(field_get:sim_msg.EgoCarInfo.start_pos)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Vec3*>(
      &::sim_msg::_Vec3_default_instance_);
}
inline ::sim_msg::Vec3* EgoCarInfo::release_start_pos() {
  // @@protoc_insertion_point(field_release:sim_msg.EgoCarInfo.start_pos)
  
  ::sim_msg::Vec3* temp = start_pos_;
  start_pos_ = nullptr;
  return temp;
}
inline ::sim_msg::Vec3* EgoCarInfo::mutable_start_pos() {
  
  if (start_pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Vec3>(GetArenaNoVirtual());
    start_pos_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.EgoCarInfo.start_pos)
  return start_pos_;
}
inline void EgoCarInfo::set_allocated_start_pos(::sim_msg::Vec3* start_pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(start_pos_);
  }
  if (start_pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      start_pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, start_pos, submessage_arena);
    }
    
  } else {
    
  }
  start_pos_ = start_pos;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.EgoCarInfo.start_pos)
}

// .sim_msg.Location location = 5;
inline bool EgoCarInfo::has_location() const {
  return this != internal_default_instance() && location_ != nullptr;
}
inline const ::sim_msg::Location& EgoCarInfo::location() const {
  const ::sim_msg::Location* p = location_;
  // @@protoc_insertion_point(field_get:sim_msg.EgoCarInfo.location)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Location*>(
      &::sim_msg::_Location_default_instance_);
}
inline ::sim_msg::Location* EgoCarInfo::release_location() {
  // @@protoc_insertion_point(field_release:sim_msg.EgoCarInfo.location)
  
  ::sim_msg::Location* temp = location_;
  location_ = nullptr;
  return temp;
}
inline ::sim_msg::Location* EgoCarInfo::mutable_location() {
  
  if (location_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Location>(GetArenaNoVirtual());
    location_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.EgoCarInfo.location)
  return location_;
}
inline void EgoCarInfo::set_allocated_location(::sim_msg::Location* location) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(location_);
  }
  if (location) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      location = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, location, submessage_arena);
    }
    
  } else {
    
  }
  location_ = location;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.EgoCarInfo.location)
}

// -------------------------------------------------------------------

// ErrorEgoCarInfo

// int32 car_id = 1;
inline void ErrorEgoCarInfo::clear_car_id() {
  car_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ErrorEgoCarInfo::car_id() const {
  // @@protoc_insertion_point(field_get:sim_msg.ErrorEgoCarInfo.car_id)
  return car_id_;
}
inline void ErrorEgoCarInfo::set_car_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  car_id_ = value;
  // @@protoc_insertion_point(field_set:sim_msg.ErrorEgoCarInfo.car_id)
}

// .sim_msg.Vec3 location = 2;
inline bool ErrorEgoCarInfo::has_location() const {
  return this != internal_default_instance() && location_ != nullptr;
}
inline const ::sim_msg::Vec3& ErrorEgoCarInfo::location() const {
  const ::sim_msg::Vec3* p = location_;
  // @@protoc_insertion_point(field_get:sim_msg.ErrorEgoCarInfo.location)
  return p != nullptr ? *p : *reinterpret_cast<const ::sim_msg::Vec3*>(
      &::sim_msg::_Vec3_default_instance_);
}
inline ::sim_msg::Vec3* ErrorEgoCarInfo::release_location() {
  // @@protoc_insertion_point(field_release:sim_msg.ErrorEgoCarInfo.location)
  
  ::sim_msg::Vec3* temp = location_;
  location_ = nullptr;
  return temp;
}
inline ::sim_msg::Vec3* ErrorEgoCarInfo::mutable_location() {
  
  if (location_ == nullptr) {
    auto* p = CreateMaybeMessage<::sim_msg::Vec3>(GetArenaNoVirtual());
    location_ = p;
  }
  // @@protoc_insertion_point(field_mutable:sim_msg.ErrorEgoCarInfo.location)
  return location_;
}
inline void ErrorEgoCarInfo::set_allocated_location(::sim_msg::Vec3* location) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(location_);
  }
  if (location) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      location = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, location, submessage_arena);
    }
    
  } else {
    
  }
  location_ = location;
  // @@protoc_insertion_point(field_set_allocated:sim_msg.ErrorEgoCarInfo.location)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sim_msg

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::sim_msg::MapPosition> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sim_msg::MapPosition>() {
  return ::sim_msg::MapPosition_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_regionBasic_2eproto
