#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/GammaCorrectionCommon.ush"

void save_color(RWStructuredBuffer<uint> buffer, int index, float4 color )
{
	color.xyz = LinearToSrgb(color.xyz);
	uint4 color_int = clamp(color * 255.f + 0.5, 0, 255);
	buffer[index] = color_int.b | (color_int.g << 8) | (color_int.r << 16) | (255 << 24);
}

int Width;
int Height;
int ScaleFactor;
Texture2D<half4> InTexture;
SamplerState InTextureSampler;
RWStructuredBuffer<uint> OutTexture;
StructuredBuffer<float2> UVMapping;
int CameraIndex;
StructuredBuffer<uint> UVCameraMapping;

[numthreads(THREADGROUPSIZE_X, THREADGROUPSIZE_Y, THREADGROUPSIZE_Z)]
void FisheyeMain(uint3 Gid : SV_GroupID,						//atm: -, 0...256, - in rows (Y)        --> current group index (dispatched by c++)
					   uint3 DTid : SV_DispatchThreadID,	//atm: 0...256 in rows & columns (XY)   --> "global" thread id
					   uint3 GTid : SV_GroupThreadID,		//atm: 0...256, -,- in columns (X)      --> current threadId in group / "local" threadId
					   uint GI : SV_GroupIndex)				//atm: 0...256 in columns (X)           --> "flattened" index of a thread within a group)
{
	if (DTid.x > Width || DTid.y > Height)
		return;

	const int index = DTid.x + DTid.y * Width;
	const uint uv_camera = UVCameraMapping[index];

	// debug show camera region
	// {
	// 	save_color(OutTexture, index, float4(float3(1, 1, 1) * uv_camera / 5, 1));
	// 	return;
	// }

	// debug show local camera direction
	// {
	// 	const float2 sample_uv = float2(UVMapping[index].x - 0.5, UVMapping[index].y - 0.5);
	// 	save_color(OutTexture, index, float4(float3(1, 1, 1) * (1.0 - sqrt(sample_uv.x * sample_uv.x + sample_uv.y * sample_uv.y)), 1));
	// 	return;
	// }
	
	if (CameraIndex != uv_camera)
	{
		return;
	}

	const float2 sample_uv = float2(UVMapping[index].x, UVMapping[index].y);
	const float4 final_color = InTexture.SampleLevel(InTextureSampler, sample_uv, 0);
	save_color(OutTexture, index, final_color);
}

void DrawStraightLine(uint2 pixel_coord, int index, int grid_interval = 120, int grid_width = 10)
{
	if (abs(pixel_coord.x % grid_interval - grid_interval) < grid_width
		|| abs(pixel_coord.y % grid_interval - grid_interval) < grid_width )
	{
		save_color(OutTexture, index, float4(1, 1, 1, 1));
	}
}

[numthreads(THREADGROUPSIZE_X, THREADGROUPSIZE_Y, THREADGROUPSIZE_Z)]
void NormalMain(uint3 Gid : SV_GroupID,						//atm: -, 0...256, - in rows (Y)        --> current group index (dispatched by c++)
					   uint3 DTid : SV_DispatchThreadID,	//atm: 0...256 in rows & columns (XY)   --> "global" thread id
					   uint3 GTid : SV_GroupThreadID,		//atm: 0...256, -,- in columns (X)      --> current threadId in group / "local" threadId
					   uint GI : SV_GroupIndex)				//atm: 0...256 in columns (X)           --> "flattened" index of a thread within a group)
{
	if (DTid.x > Width || DTid.y > Height)
		return;

	const int index = DTid.x + DTid.y * Width;

	const float2 sample_uv = float2(UVMapping[index].x, UVMapping[index].y);
	const float4 distort_color = InTexture.SampleLevel(InTextureSampler, sample_uv, 0);
	save_color(OutTexture, index, distort_color);
	
	// save_color(OutTexture, index, InTexture.SampleLevel(InTextureSampler, float2(DTid.x, DTid.y) / float2(Width, Height), 0));
	
	// debug 
	// save_color(OutTexture, index, float4(0, 0, 0, 1));
	// DrawStraightLine(uint2(sample_uv.x * Width, sample_uv.y * Height), index);
	// DrawStraightLine(uint2(DTid.x, DTid.y), index);
}

