
[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=2C56AFE34F9A45A4B2D3996A6C7201B4

[Mode]
Asynchronous=false
SyncOneFrame=false
SnapGround=true
SyncModeWait=500
bLoadHadmap=false
;0:ROUTINGMAP,1:MAPENGINE
MapMode=1

[Language]
EnviromentVar=TADSIM_LANGUAGE
EnglishValue=en

[GlobalSettings]
LobbyMapPath=/Game/Basic

[Sensor]
bUseLocalScenarioDir=false
TadsimConfigPath=./
CameraSaved=false
PublicMsg=false
CameraMemShare=false
CameraGPUShare=false
CameraStyle=false
JpegQuality=85

[MapIndex]
;高精度地图名称
;预设场景
sim_map_downtown_001.*.xodr=36

[MapName]
;地图title
0=NoMap
36=SIM_CITY

[MapPath]
;Level路径
NoMap=/Game/Basic
SIM_CITY=/Game/Basic

[MapOrigin]
;参考点
/Game/Basic=0 0 0
; bUseMapDecrypt=false
; DecryptFilePath=
SnapRange=300 -300

[TypeDef]
transport/Type-1=transport/SUV.havalH7001
transport/Type511=transport/MPV.MPV_002

[/TypeList]
transport/SUV.havalH7001=Blueprint'/Game/Blueprints/Vehicle/BP_Vehicle_SUV_HavalH7_1.BP_Vehicle_SUV_HavalH7_1'
transport/MPV.MPV_002=Blueprint'/Game/Blueprints/Vehicle/BP_Vehicle_youjia_shangwuche.BP_Vehicle_youjia_shangwuche'
