
[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=2C56AFE34F9A45A4B2D3996A6C7201B4

[Mode]
Asynchronous=false
SyncOneFrame=false
SnapGround=true
SyncModeWait=500
bLoadHadmap=false
MapMode=1

[Language]
EnviromentVar=TADSIM_LANGUAGE
EnglishValue=en

[GlobalSettings]
LobbyMapPath=/Game/Basic

[Sensor]
bUseLocalScenarioDir=false
TadsimConfigPath=./
CameraSaved=false
PublicMsg=true
CameraMemShare=false
CameraGPUShare=false
CameraStyle=false
JpegQuality=85
LidarSaved=false
LidarCoordType=None
;;vehicle,enu
LidarMethod=raycast
;;depth,raycast
LidarThreads=5
LidarDN=5
LidarDualReturn=false
LidarFrameAlign=false
LidarUtcOffect=0

[MapIndex]
shanghai.xodr=1
sim_map_downtown_001.*.xodr=36

[MapName]
0=NoMap
1=SH6
36=SIM_CITY

[MapPath]
NoMap=/Game/Basic
SH6=/Game/Horizon/Map/City_ShangHai_Small
SIM_CITY=/Game/Basic

[MapOrigin]
/Game/Basic=0 0 0
/Game/Horizon/Map/City_ShangHai_Small=0 0 0
SnapRange=300 -300

[TypeDef]
transport/Type-1=transport/SUV.havalH7001
transport/Type511=transport/MPV.MPV_002

[/TypeList]
transport/SUV.havalH7001=Blueprint'/Game/Blueprints/Vehicle/BP_Vehicle_SUV_HavalH7_1.BP_Vehicle_SUV_HavalH7_1'
transport/MPV.MPV_002=Blueprint'/Game/Blueprints/Vehicle/BP_Vehicle_youjia_shangwuche.BP_Vehicle_youjia_shangwuche'
