FROM hub.hobot.cc/imagesys/4dlabel:tadsim-desktop-ubuntu20.04

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
    libegl1 libxext6 gawk bison

COPY vulkan/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
COPY vulkan/nvidia_icd.json /usr/share/vulkan/icd.d/nvidia_icd.json

COPY vulkan/nvidia-driver-535/* /usr/lib/x86_64-linux-gnu/

RUN ln -s /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.535.98 /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.0
RUN ln -s /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.535.98 /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.1
RUN ln -s /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.535.98 /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.2
RUN ln -s /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.535.98 /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0